### PR TITLE
Fixes issue #796 - Enhance style and functionality of settings page

### PR DESCRIPTION
**Pull request by tstreamDOTh**
Fixes issue #796 - Enhance style and functionality of settings page 
Changes:

- Added save button to each page
- Aligned text on right side pages on the left and implement similar padding to twitter
- Reduced the margin between left and right section of settings panel. 
- Moved the "theme" option to a dedicated tab 
- Changes the background color to match with susi.skills.ai

Demo Link: http://well-made-value.surge.sh/

Screenshot:
image

### CODE REVIEW

**Comment by tstreamDOTh** [comment]
@isuruAb @DravitLochan @rishiraj824 fixed the travis error.

**Comment by hpdang** [comment]
Good job!

**Comment by mariobehling** [comment]
This is a good first step, but it does not solve the issue entirely. Also the theme details are no present in two tabs. Please follow the example of Twitter more closely.

**Comment by tstreamDOTh** [comment]
@mariobehling Sure. I will follow up and make further improvements.

**Pull request merged**
