### PR TITLE
Add functionality for google login

### PR DESCRIPTION
**Pull request by akshatnitd**
Partial fix for issue #935

Changes: Added google login feature using a package

Demo Link: [yielding-flock.surge.sh](http://yielding-flock.surge.sh
)

Screenshots for the change: 
screenshot from 2017-12-16 01-04-02

P.S. : An API for handling logins via social sites needs to be exposed.

### CODE REVIEW

**Comment by akshatnitd** [comment]
@isuruAb @madhavrathi Please review :) Have also opened up a issue (fossasia/susi_server#625), to solve the problem completely.

**Comment by anshumanv** [comment]
Nice approach @akshatnitd :smile:

**Comment by akshatnitd** [comment]
@anshumanv You are right :D All other changes can be made, once the social login API is ready and a token is returned from the server

**Comment by akshatnitd** [comment]
@stealthanthrax I had worked on the 2nd part of the issue, since it had been over 10 days that the issue was open and I thought of collaborating.

@anshumanv @isuruAb If required, I can close the PR and @stealthanthrax can go ahead with it

**Comment by stealthanthrax** [comment]
Please let me know, so I can make another PR.

**Comment by stealthanthrax** [comment]
@mariobehling

**Comment by mariobehling** [comment]
Please see my comments for Facebook. An integration should happen similarly as it is done in Pinterest and involve the server.

**Comment by psikarwal** [comment]
@mariobehling how would the server be involved, means what is the exact approach you want. It will be very good if you provide some details. 😃

**Pull request closed without merging**
