### PR TITLE
Added French as an option in Text Language settings

### PR DESCRIPTION
**Pull request by sayak119**
Fixes issue #937 

Changes: Added French as an option in Text Language Settings

Demo Link: http://discreet-match.surge.sh/

Screenshots for the change: 

screenshot from 2017-12-05 04-41-20

### CODE REVIEW

**Comment by Remorax** [comment]
LGTM 👍

**Comment by sayak119** [comment]
@isuruAb @madhavrathi please review and merge

**Comment by sayak119** [comment]
@madhavrathi @isuruAb @anshumanv please review and merge.

**Comment by aashutoshrathi** [comment]
Anyways, squash would be appreciated. 😉

**Comment by sayak119** [comment]
@aashutoshrathi I couldn't find any resources to squash the commits which were edited using github's editor.

**Comment by sayak119** [comment]
@madhavrathi Please merge this :-)

**Comment by chashmeetsingh** [comment]
@sayak119 please take a look at [this blogpost](https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/) which might help you with the squash thing.

**Comment by sayak119** [comment]
@chashmeetsingh  thanks for the guide :-) but git rebase --interactive HEAD~(number) won't show the commits you made using github's online editor.

**Comment by rishiraj824** [comment]
@sayak119 Please backup your changes and sync your fork with the upstream and then commit your changes. Thanks!

**Pull request merged**
