### PR TITLE
Fixes #684 Fixed TopBar in firefox

### LINKED ISSUE #684: Test UI on Firefox and fix bugs.
**Actual Behaviour**

The UI is not stable in Firefox. 

**Expected Behaviour**

The UI should work on all the browsers seamlessly

**Would you like to work on the issue?**

Anyone can contribute and solve if there are any bugs.

### PR DESCRIPTION
**Pull request by madhavrathi**
Fixes issue #684 (Partially)

Changes: Fixed TopBar in firefox
Demo Link: http://susifirefox.surge.sh/overview

Screenshots for the change: 
firefox_bar
@rishiraj824 @isuruAb @uday96 Please run the demo link on firefox to review this PR.
Thanks

### CODE REVIEW

**Comment by uday96** [comment]
@madhavrathi Please mention that the buttons were aligned in the top bar in the issue page also to keep track of the bugs found and fixed :+1:

**Comment by mariobehling** [comment]
Unfortunately I just saw now, that your change moved the white area on Chromium. Please fix it. It should be on the blue area.

screenshot from 2017-08-07 08-59-43

**Comment by madhavrathi** [comment]
@mariobehling In my chromium browser, the top bar looks like this : 
chromium
I am using: Version 59.0.3071.109 (Developer Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by mariobehling** [comment]
Same browser Version 59.0.3071.109 (Developer Build) Built on Ubuntu

screenshot from 2017-08-07 18-04-43

**Comment by madhavrathi** [comment]
@mariobehling I have fixed this in PR: https://github.com/fossasia/chat.susi.ai/pull/696
Please check the deployment link to cross verify: http://magenta-effect.surge.sh/overview

**Pull request merged**
