### PR TITLE
Fixes: #797 -Settings Page Add mobile section

### PR DESCRIPTION
**Pull request by isuruAb**
#855 Fixes issue #797 
Changes: 

- [x] Finished UI component
- [x]  Save to server

Demo Link: http://isuruab.surge.sh/
Screenshots for the change: 

screen shot 2017-10-15 at 8 06 59 am

@madhavrathi  @rishiraj824  please review this

### CODE REVIEW

**Comment by tabesin** [comment]
Zaire +243

**Comment by isuruAb** [comment]
@tabesin  yes . if we use node module that @madhavrathi  suggested we have the above issue. so it is better to maintain our own data set for get the country list and country code list. Do you know any good solution for this?

**Comment by mariobehling** [comment]
Please sync with base branch.

**Comment by isuruAb** [comment]
Updated the branch. @mariobehling  could you please review this again.

**Pull request merged**
