### PR TITLE
fix responsiveness of all pages for smaller screens

### PR DESCRIPTION
**Pull request by madhavrathi**
Fixes issue #654 

Changes: Fixed the responsiveness of all pages for smaller screens

Demo Link: http://susi-madhav.surge.sh/overview

Screenshots for the change: 

m1

m2

@rishiraj824 @uday96 @isuruAb Please review and let me know if any component needs to fixed.
Thanks

### CODE REVIEW

**Comment by madhavrathi** [comment]
@rishiraj824 @uday96 @isuruAb Please review this : http://susi-madhav.surge.sh/overview
Thanks

**Comment by isuruAb** [comment]
when the screen width is 310px it looks like this. if we can align them to center that would be good.
screen shot 2017-08-03 at 6 43 24 am

there is a horizontal scroll when the screen width is less than 300px
screen shot 2017-08-03 at 6 47 47 am

**Comment by mariobehling** [comment]
@madhavrathi As discussed please fix the footer alignment of the SUSI logo and text in the same way as before in subsequent PRs.
screenshot from 2017-08-03 16-21-04

**Comment by madhavrathi** [comment]
@mariobehling Okay, I will fix this in next PR.

**Pull request merged**
