### PR TITLE
Removes horizontal scrollbar from the iframe

### LINKED ISSUE #1143: Remove Scrollbar from the iframe that loads at the starting of the website using JavaScript so that it still renders perfectly on all browsers.
**Actual Behaviour**
There's a horizontal scrollbar on the iframe that loads up at the starting of the webpage.

**Expected Behaviour**
The scrollbar seems unnecessary and hence, should be removed.

**Screenshots of the issue**

Current state:
scrollbarold

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by Akshat-Jain**
Fixes #1143 

**Changes:** Removes the horizontal scrollbar from the iframe that loads at the starting of the website using JavaScript so that it still renders perfectly on all browsers.

**Demo Link:** https://pr-1143-fossasia-susi-web-chat.surge.sh

**Screenshots for the change:** 

**Current state:**
scrollbarold

**Updated state:**
scrollbarnew

### CODE REVIEW

**Comment by gabru-md** [comment]
@Akshat-Jain the branch is out of date. Can you please merge the latest changes from the master branch ?
:)

**Comment by Akshat-Jain** [comment]
@gabru-md Updated the branch :-)

**Comment by duttaditya18** [comment]
3verything looks good! Awesome 👍

**Comment by Akshat-Jain** [comment]
@duttaditya18 Thanks :)

**Pull request merged**
