### PR TITLE
Allows sending feedback on old messages as well

### LINKED ISSUE #930: Only one of the talk by susi can be liked
**Actual Behaviour**

You can like only one message sent by susi(most recent only)

**Expected Behaviour**

The feature should also allow the user to like/dislike old messages

**Steps to reproduce it**

Talk to susi and send her about 2-3 messages. Try liking/disliking each of them

**Would you like to work on the issue?**
I might need assistance, but I will work on the issue.
Issue be assigned to @developeralfa

### PR DESCRIPTION
**Pull request by abishekvashok**
Fixes #930

Changes:
Fixes bug of not being to send and change feedback of old messages. Now
we can allow sending feedback of old messages as well.

Demo Link: https://pr-1054-fossasia-susi-web-chat.surge.sh

Screenshots for the change: 
screenshot_20180114_205524
screenshot_20180114_205530

### CODE REVIEW

**Comment by abishekvashok** [comment]
Ping @daminisatya

**Comment by abishekvashok** [comment]
Maybe you can do a merge @daminisatya

**Comment by daminisatya** [comment]
@abishekvashok I was waiting for the build to pass, since i updated the branch again

**Comment by abishekvashok** [comment]
Okay cool @daminisatya

**Pull request merged**
