### PR TITLE
Implement same top bar and fix spacing issue with menu

### LINKED ISSUE #1437: Add some spacing for menu
**Actual Behaviour**
There is no spacing to the right of menu

**Expected Behaviour**
There should be some spacing to the right

**Screenshots of the issue**
m1

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by PrP-11**
Fixes #1437 

Changes: 
- Add some spacing to the right of menu like accounts
- Implement same top bar on all routes

Demo Link: https://pr-1440-fossasia-susi-web-chat.surge.sh

Screenshots for the change: 
m1

### CODE REVIEW

**Comment by PrP-11** [comment]
@Akshat-Jain I agree with with you but I didn't cut the width, I added some margin to the right. I will check whats causing this change.

**Comment by mariobehling** [comment]
Please also check that this works on all routes including overview etc.

**Comment by PrP-11** [comment]
@Akshat-Jain Fixed it

**Comment by Akshat-Jain** [comment]
Agreed with @DNS-404. Please make the changes on all routes. Thanks :-)

**Comment by PrP-11** [comment]
@Akshat-Jain @DNS-404 @anshumanv I have opened #1455 to implement same top bar on every route. I will refractor the code to implement single top bar instead of two which we have currently.

**Comment by anshumanv** [comment]
You don't seem to understand the requirement.

**Comment by PrP-11** [comment]
@Akshat-Jain @DNS-404 @anshumanv I dropped that idea and fixed it. Please review

**Comment by DNS-404** [comment]
@PrP-11 Please update the branch.

**Comment by PrP-11** [comment]
@DNS-404 Updated the branch

**Pull request merged**
