### PR TITLE
Fixes #716  #713 - Use existing Static App Bar on Settings page

### LINKED ISSUE #716: Use existing Static App Bar on Settings page
**Actual Behaviour**

It uses  another it's own app bar on same page.
so developers need to change two places when they need to do a one single thing.

**Expected Behaviour**

We can use existing Static app bar on settings page.
we can check the page and show and hide the  left navigation and drawer on settings page

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by isuruAb**
Fixes issue #716   #713

Changes: 

- Used existing StatiAppBar component on settings page and reduces the complexity of Settings page.
- Previously Sign Up form was not working when we trying to open it from Login Dialog.
-options drop down comes under the correct position of the app bar

Demo Link: http://isuruab.surge.sh/settings

Screenshots for the change: 
screen shot 2017-08-12 at 2 14 08 pm

@sudheesh001  @madhavrathi  @uday96  please review this

### CODE REVIEW

**Comment by mariobehling** [comment]
* There are two times "Select Language". What is the difference? How can this be better distinguished?
* Theme Settings don't seem to work. Nothing happens when changing it. There should be a preview or something. Maybe we take it out?

**Comment by isuruAb** [comment]
@mariobehling one "language " drop down is for selecting a text to speech language. other one is for text replies. 

#719  I'm working on custom theme and ready made theme issue here.will send PR asap

**Comment by mariobehling** [comment]
>  one "language " drop down is for selecting a text to speech language. other one is for text replies.

@isuruAb How should users guess this. Please make this clear in the UI.

**Comment by isuruAb** [comment]
@mariobehling  done requested changes. please check the  link again
http://isuruab.surge.sh/settings

**Comment by isuruAb** [comment]
@mariobehling  i have already started working on that issue I will send a PR for that issue asap

**Comment by uday96** [comment]
@isuruAb Resolve conflicts. Also maybe we can change the first language button as Text To Speech Settings.

**Comment by isuruAb** [comment]
@uday96  resolve conflicts please check again

**Comment by mariobehling** [comment]
Thanks.

**Pull request merged**
