### PR TITLE
Fix #861 UI improvements in Login screen

### LINKED ISSUE #861: UI improvements in Login screen
**Proposed changes**
- Change the font of "Login to SUSI"
- Change the input type of email field from `text'` to `email`
- Remove the default orange background of text fields in Chrome browser
- Show loading status while logging in.
**Screenshots of the issue**
image

**Would you like to work on the issue?**
 Yes

### PR DESCRIPTION
**Pull request by ismaeldcom**
Fixes issue #861 

Changes: 
* Remove input autofill yellow background
* Remove custom font family from loginForm h3
* Change login email field type from to email
* Show loading status while logging in

Demo Link: http://cold-lift.surge.sh/

Screenshots for the change: 
captura de pantalla 2017-10-24 a las 14 58 56

### CODE REVIEW

**Comment by rishiraj824** [comment]
@ismaeldcom Please squash your commits into one. Thanks !

**Comment by ismaeldcom** [comment]
@rishiraj824  I just squash the commits.
Anyway, isn't it easier to use the "squash and merge" option from github?

**Comment by ismaeldcom** [comment]
@isuruAb I've never used codacy before, but what I see is a positive pull request. Something to check?

**Comment by ismaeldcom** [comment]
@hkedia321 Thanks for that
I didn't know this solution, only the shadow workaround.
I just push it.

**Pull request merged**
