### PR TITLE
fix: Integrate getAvatar.png API

### PR DESCRIPTION
**Pull request by nemaniarjun**
This commit integrates the getAvatar api from susi-api
to fetch user images instead of fetching directly from
Gravatar.

Closes https://github.com/fossasia/chat.susi.ai/issues/1540

Changes: changed the url to fetch the image from. Removed the gravatar url from `urls.js`

Demo Link: https://pr-[ADD_PULL_REQUEST_NUMBER_HERE]-fossasia-susi-web-chat.surge.sh

Screenshots for the change:

### CODE REVIEW

**Comment by nemaniarjun** [comment]
@Akshat-Jain

**Comment by samagragupta** [comment]
Please update your demo link .

**Comment by nemaniarjun** [comment]
Sorry I am on a vacation till Monday. Will get back to this then! :)

**Comment by isuruAb** [comment]
@nemaniarjun  could you please work on requested changes ?

**Pull request merged**
