### PR TITLE
Fixes Recaptcha console error message, XHR warning #1513

### LINKED ISSUE #1513: Recaptcha console error message even if Recaptcha is not used
Recpatcha messages appear in the console even if Recaptcha is not used on the specific page.

`jquery.js:9488 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #1513 
Changes: 

Solves below 2:
1. Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
2. reCAPTCHA couldn't find user-provided function: onloadCallback

screen shot 2018-08-25 at 2 26 18 pm

Demo Link: https://pr-1513-fossasia-susi-web-chat.surge.sh (Updated)

### CODE REVIEW

**Comment by fragm3** [comment]
The travis is not due to this PR.

**Comment by fragm3** [comment]
Rebuilding the travis solves this

**Comment by akshatnitd** [comment]
@fragm3 The recaptcha msgs are still being shown on the console. Making the AJAX call asynchronous doesn't remove the captcha msg.

**Comment by fragm3** [comment]
@akshatnitd The Issue name is misleading, see the `[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.` warning on first line of console. It has nothing to do with recaptcha.

**Comment by akshatnitd** [comment]
@fragm3 I understand that we are `async` false and it gives an error. But, the issue is mainly for removing the recaptcha message. The highlighted text in the issue description was just a lead, to solve the issue.

**Pull request closed without merging**
