### PR TITLE
Corrects alignment of left navigation bar of Settings

### LINKED ISSUE #1222: Display list of connected devices on the Web Client
**Actual Behaviour**

There is no section for Devices on the web client.

**Expected Behaviour**

The devices which are linked to the logged in user should be fetched from the APIs created in [susi_server #740](https://github.com/fossasia/susi_server/pull/740) and then be displayed on the web client.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Akshat-Jain**
Fixes #1222 

**Changes:** Corrects the alignment of left navigation bar of Settings.

**Demo Link:** https://pr-1265-fossasia-susi-web-chat.surge.sh

**Screenshots for the change:** 

Settings page when we are logged in -  
loginsettings

Settings page when we are not logged in -
logoutsettings

### CODE REVIEW

**Comment by akshatnitd** [comment]
deepinscreenshot_select-area_20180529043058
 The white space shouldn't be there

**Comment by Akshat-Jain** [comment]
@akshatnitd I think it looks just fine even with the whitespace. Otherwise the height of the components will change depending on their contents, and it doesn't look good and isn't consistent. This one looks better in my opinion :-)

**Comment by mariobehling** [comment]
@hkedia321 How can you approve this PR when Travis is failing?

**Comment by anshumanv** [comment]
@Akshat-Jain someone already owns the URL on which the pr_deploy script is trying to deploy, whoever owns it has to either `teardown` the url and you need to restart travis job to do surge deployment otherwise the travis won't pass, nothing wrong with the code and this won't break the build of the master branch.

**Comment by hkedia321** [comment]
@mariobehling The travis seems to be failing for some other reason and not due to changes in this PR. I have updated my review status. Will keep this in mind from next time.

**Comment by Akshat-Jain** [comment]
@mariobehling @anshumanv @hkedia321 Fixed the Travis issues :-)

**Pull request merged**
