### PR TITLE
Fixes #582 - Improve the design of All Popups

### LINKED ISSUE #582: Improve the design of all Popups
**Actual Behaviour**

The current popups do not follow the login pop up's theme.

**Expected Behaviour**

The current login popup should be the standard for all pop ups to occupy more space and for a clean UI.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by rishiraj824**
Fixes issue #582

Changes: 
- Changes the design of all popups similar to login pop up
- Added hover styles to all the text fields
- Added `Open Sans` font to headers
- Changed the close button to the top right corner as a symbol

Demo Link: 
http://susi-popups.surge.sh

Screenshots for the change: 
screenshot from 2017-07-24 00 32 09

### CODE REVIEW

**Comment by mariobehling** [comment]
Why is this a priority now, while we have other priority issues?

The implementation has a number of problems.

* Popups should not go on top of other popups
* Signup has different font
* There is not enough space around some text areas

**Comment by rishiraj824** [comment]
@mariobehling Will make the required changes :+1:

**Comment by rishiraj824** [comment]
Made the changes. :+1: 
 - The font of all headings is `Open Sans`. 
 - Added spacing to the text area. 
 - The forgot password pop up is over the Login pop up as it is in http://chat.susi.ai. I haven't made any changes to that.

**Comment by mariobehling** [comment]
Please do improve the popups more substantially.
* Avoid popups that are showing up on top of each other. Just because it was "always" like that does not mean it should. 
* Increase the white space. The text on the edges is too close to the border
screenshot from 2017-07-24 09-37-06
* Test outcome on mobile resolutions and ensure it works as desired

**Comment by rishiraj824** [comment]
@mariobehling Got it. Will improve those.

**Comment by rishiraj824** [comment]
@mariobehling Please check. I've removed the effect of one pop up appearing over another. I've also tested for mobile too. And now there's white space around the text.
screenshot from 2017-07-25 00 14 25
screenshot from 2017-07-25 00 14 37

**Comment by mariobehling** [comment]
Please also ensure the "Settings" pop up works as expected. At the moment the font changes.

**Comment by rishiraj824** [comment]
@mariobehling Done.

**Comment by mariobehling** [comment]
Settings still not working as expected. Fonts and font size has changed.
screenshot from 2017-07-25 10-41-24

**Comment by rishiraj824** [comment]
screenshot from 2017-07-25 16 08 18
Please check.

**Comment by mariobehling** [comment]
Thank you.

**Pull request merged**
