### PR TITLE
Fixes: #458 - Lighten up the standard design

### PR DESCRIPTION
**Pull request by isuruAb**
Fixes issue #458 

Changes: change the theme styles according to the market leaders.

Demo Link: http://isuruab1.surge.sh/

Screenshots for the change: 

screen shot 2017-07-18 at 8 09 11 am
@madhavrathi  @rishiraj824  @uday96 please review

### CODE REVIEW

**Comment by mariobehling** [comment]
Improve the whole UI color set and tell us the color codes of each item:
* Background
* Chat background
* Chat bubbles
* Other UI messages, e.g. notifications
* Top bar
* Buttuns
* Any other font
* Anything else

**Comment by isuruAb** [comment]
@uday96  @rishiraj824  I will reduce the space by  aligning  time to left.  I got these colours and design from here https://assistant.google.com

**Comment by isuruAb** [comment]
- Background -#fffff
-  Chat background -#f5f4f6
- Chat bubbles - SUSI #ffffff User #e0e0e0
- Top bar #0084ff
- Buttons #0084ff
- Any other font  "Product Sans", sans-serif
- font colour #001d38

preview URL: http://isuruab1.surge.sh/

**Comment by mariobehling** [comment]
Please resolve conflicts. What about the triangle tips?

**Comment by mariobehling** [comment]
* Please document the colors in the Readme.md (include a small color sample area).
* What are the colors for the "loading bubbles" and the "thumbs"
* What is the font size of the different areas?

**Comment by rishiraj824** [comment]
screenshot from 2017-07-19 20 46 47
RSS feeds have no borders.

**Comment by madhavrathi** [comment]
@isuruAb please consider Mario's comment about adding triangle tips to chat bubbles.

**Comment by mariobehling** [comment]
@isuruAb 

> What about the triangle tips?

**Comment by isuruAb** [comment]
@mariobehling  "triangle tips" are not there in google assistant and Allo

**Comment by mariobehling** [comment]
@isuruAb Please keep them for now and we check how it looks like. There were some effects implemented recently.

Please resolve conflicts.

**Comment by isuruAb** [comment]
@mariobehling triangle tips Added  please review again. 
@rishiraj824  @uday96  @madhavrathi  please review

**Comment by mariobehling** [comment]
@isuruAb Thumbs up and down are no longer next to the time. Please move them back.

**Comment by mariobehling** [comment]
Ok, this was fixed in another PR. Please resolve conflicts.

**Comment by isuruAb** [comment]
@mariobehling  resolved conflicts.please review this again please.

**Comment by mariobehling** [comment]
Well-done.

**Pull request merged**
