### PR TITLE
Incorrect positioning in login form corrected

### LINKED ISSUE #2043: Incorrect positioning in login form
**Actual Behaviour**
Password field and login text in login buttonis wrongly positioned in login form.

**Expected Behaviour**

Password field should be styled same as email field.

**Screenshots of the issue**

1f215213-adaf-45aa-8e3e-2c9665a3e076 png

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by ashwaniYDV**
Fixes #2043

Changes: Updated margins of div in login form

Demo Link: https://pr-2043-fossasia-susi-web-chat.surge.sh

Screenshots for the change: 

Before fixing issue
1f215213-adaf-45aa-8e3e-2c9665a3e076 png

After fixing issue
0c615ee4-8ab6-4027-85f3-5a88a75f8f79 png

### CODE REVIEW

**Comment by rajshah9914** [comment]
@ashwaniYDV Please checkout the #1989 issue first, this was already opened  whose PR I had already sent and had partially solved the issue and waiting for response other side. Not even got a day to solve this issue.. I could had done it before but delayed due to lack of response from other side..
with_pr

**Comment by rajshah9914** [comment]
@ashwaniYDV This would save time of both and PR's won't overlap, and just a suggestion, please check if the issue opened already exists before creating a new one.

**Comment by AakashMallik** [comment]
> @ashwaniYDV Please checkout the #1989 issue first, this was already opened whose PR I had already sent and had partially solved the issue and waiting for response other side. Not even got a day to solve this issue.. I could had done it before but delayed due to lack of response from other side..
> with_pr

Yeah, I was looking for your PR coz I felt I had seen this issue had been raised before. @ashwaniYDV Please close this PR and let @rajshah9914 fix this as he had already started working on this.

**Comment by AakashMallik** [comment]
@ashwaniYDV  Did you just choose to ignore this text? 
screenshot-github com-2019 02 14-15-04-07

**Comment by ashwaniYDV** [comment]
Thank you #AakashMallik. 
I'll always check if same issue is opened before.

**Pull request closed without merging**
