### PR TITLE
Fixes #277 - Implement Voice on Chrome

### LINKED ISSUE #277: Implement Voice on Chrome
The Google Search shows a voice activation icon that can be used in the Chrome Browser.

Please implement the same feature on the web chat.
screenshot from 2017-06-17 16-43-00

### PR DESCRIPTION
**Pull request by rishiraj824**
**Fixes issue #277**

**Changes:**
- Added Voice to text feature for Chrome
- Testing for all browsers handled, Mic will only appear for browsers supporting Speech Recognition API
- Added loading icon while STT is happening
- Mic will be off automatically after a pause
- Send button enabled as soon as one starts to type.
- Kept Mic as default following the other clients in the market
- Automatically sends the message after STT conversion.

**Demo Link:**
Use Chrome to test
http://susivoice.surge.sh

**Sceenshot**
localhost-3000- iphone 6

### CODE REVIEW

**Comment by isuruAb** [comment]
if we can send it automatically after asking the question that would be nice

**Comment by rishiraj824** [comment]
@isuruAb What if the conversion wasn't as expected and was sent, wouldn't the user want to edit it according to him?

**Comment by mariobehling** [comment]
@rishiraj824 Please try out Google search and see how voice input works here. There is a speak now screen and after the user speaks there is an immediate output without any other user interaction required.

Please implement it in the same way.
screenshot from 2017-07-05 20-59-10

**Comment by rishiraj824** [comment]
@mariobehling Ok, got it! I will implement it in the same way.

**Comment by rishiraj824** [comment]
@mariobehling Please check at http://susivoice.surge.sh, messages will be sent automatically now.

**Comment by mariobehling** [comment]
@rishiraj824 Good job. Did you test it with Google? Do you see the "Speak Now" page? And did you get the answer rendered as voice as well? Please follow the implementation more closely.

**Comment by rishiraj824** [comment]
@mariobehling Yes I tested it with Google, I will surely add Speak Now Page, and render voice answers in the upcoming PRs. Please merge this for now.

**Pull request merged**
