### PR TITLE
Fixes: #641 -Use same width of content across all pages

### PR DESCRIPTION
**Pull request by isuruAb**
Fixes issue #641

Changes:  change the widths of all pages. optimise the responsive views.
 
Demo Link: http://isuruab.surge.sh/overview

Screenshots for the change:

### CODE REVIEW

**Comment by mariobehling** [comment]
Please move the phone images a bit more to the right. They are leaning a bit too much to the left.
screenshot from 2017-07-31 21-36-39

**Comment by mariobehling** [comment]
Issue is apparently not fixed.

I suggest you align all pages same as the front page. See screenshot below for the front page.
screenshot from 2017-07-31 21-53-19

**Comment by isuruAb** [comment]
@mariobehling  @rishiraj824  @uday96  @madhavrathi  please review this

**Comment by rishiraj824** [comment]
@isuruAb Please check the link if it's updated with the lates changes. Thanks

**Pull request closed without merging**
