### PR TITLE
Add Dutch Translation, Fix errors in existing Translations

### PR DESCRIPTION
**Pull request by 0x48piraj**
# Fixes issue #999

Changes: 
- Added dutch support to **susi.ai** :tada: 
- Done all strings conversion, checked them natively too ! :heart_decoration: 
- Corrected some errors in `en.json`

_**Demo Link: Not needed yet!**_ _(Anyways, Looking cool: https://pr-1000-fossasia-susi-web-chat.surge.sh/)_

Screenshots for the change: 
No use.

### CODE REVIEW

**Comment by 0x48piraj** [comment]
## 1000th PR :tada: :sparkles: :heart_decoration: :1st_place_medal: 

Ping @rishiraj824 :100:

**Comment by 0x48piraj** [comment]
Different fixes, different commits.
All are atomic, two of first ones are not that usefull but squashing will undo all.
Please accept this time.

**Comment by 0x48piraj** [comment]
Pin @rishiraj824 @mariobehling :heart_decoration:

**Comment by 0x48piraj** [comment]
@isuruAb https://github.com/fossasia/chat.susi.ai/pull/1002 is failing due to this.

Both are linked.
Please merge this, the Travis Check will pass :100:

**Comment by gabru-md** [comment]
Ping @madhavrathi

**Pull request merged**
