### PR TITLE
Added lottie and started the build of a better introductory section

### PR DESCRIPTION
**Pull request by Sid911**
Steps complete of issue #1785 
- [x] Add Lottie to the project and verify if there are any compatibility issues
- [x] Add an example usage

**Changes:** 

- Added Lottie to the package.json and checked for any compatibility issues
- Added 2 animations including  https://lottiefiles.com/share/saepEj and https://lottiefiles.com/share/BZprDl
- Used first animation in the new comer's dialog box

Demo Link: https://pr-1780-fossasia-susi-web-chat.surge.sh

Screenshots for the change: 
image
image
image

I have started adding new animations but I am waiting if the design changes are done in this thread https://github.com/fossasia/chat.susi.ai/issues/1641

### CODE REVIEW

**Comment by Sid911** [comment]
I am not sure hot to add the demo link...

**Comment by AakashMallik** [comment]
@Sid911 Try adding this in the Overview component. Plus your work seems incomplete if that video does not contain the features Susi has.

**Comment by rajvaibhavdubey** [comment]
@Sid911 I think that the logo which is appearing should be similar to original.

**Comment by Sid911** [comment]
@rajvaibhavdubey Actually I am changing somethings, so if I could get WIP label it would be awesome

**Pull request closed without merging**
