### PR TITLE
Fixes #456 - Create an overview page

### LINKED ISSUE #456: Create an overview page
Currently we don't have a good overview page. Please create one following https://assistant.google.com 

Intended domain: chat.susi.ai/overview

### PR DESCRIPTION
**Pull request by rishiraj824**
Fixes issue #456 

Changes: 
Go to the dropdown available on the right and click on *Overview*
- Added Overview Page at `/overview`

Demo Link: 
http://susi-overview.surge.sh

### CODE REVIEW

**Comment by rishiraj824** [comment]
@uday96 Yes its disabled for now. But it still shows the error, but there would be no harm whatsoever in merging the PR as the errors are coming from using `!important`

**Comment by rishiraj824** [comment]
@mariobehling Will, update with the changes. Please tell if any changes are required in the text and the images too.

**Comment by mariobehling** [comment]
> Please tell if any changes are required in the text and the images too.

Get the layout up and running in a proper way. More details will come after that. Not sure, why this takes so long.

**Comment by rishiraj824** [comment]
@mariobehling Yes, I am making the changes. Will push it in a few minutes.

**Comment by mariobehling** [comment]
@rishiraj824 Actually this issue has been very clear. Please avoid giving impressions like "oh I cannot continue, because I need info xyz" and then you ask for more input. I have already given feedback. We need to see code and outcome from you. If people have more comments they will add them. Provide code and outcome instead of stirring up conversations!

**Comment by rishiraj824** [comment]
@mariobehling Extremely sorry for creating confusions.  Not giving a reason for not able to submit it on time, but I had to travel to my college due to an emergency. I assure you it won't happen again. I have made the changes to the TopBar. Please check, thanks! Also if there's an issue with the ChatApp not working it has been fixed in https://github.com/fossasia/chat.susi.ai/pull/496

**Comment by mariobehling** [comment]
Please change: 
* Background should be white
* Use same dropdown as on main page
screenshot from 2017-07-16 13-34-59

**Comment by mariobehling** [comment]
Also add an image on the top similar to:
screenshot from 2017-07-16 13-40-26

**Comment by mariobehling** [comment]
Add this video to a "Watch" button: https://www.youtube.com/watch?v=tIG5griC-G0&t=26s

**Comment by mariobehling** [comment]
Spellcheck! What is wrong here? Find at least two mistakes!

> Search for the capital of vietnam or find translations in different languages. Ask Susi for your location, and what the weather’s like when you get there.

**Comment by mariobehling** [comment]
Expand the text: "SUSI can listen to you through..." to:

SUSI can listen to you through the Mic and answer back on your Speaker. You can activate the assistant saying "Hi SUSI" already on many clients and devices. The more you talk with SUSI the better it gets. You can even tell SUSI to remember things.

**Comment by mariobehling** [comment]
Add section on the bottom:

## Integrate SUSI with your favorite chat services and social networks.

SUSI.AI already runs on many chat services and social networks. We are developing plugins for all major services including Twitter, Facebook, Line, Whatsapp, Viber, Slack, Gitter and Wechat. Just set up SUSI on your channel and add @susi in your conversations and SUSI is ready to help.

**Comment by mariobehling** [comment]
Add section:

## Safe and secure.

SUSI.AI is Open Source. The code is always available for security reviews and can be improved by anyone with the knowledge and understanding online.

**Comment by mariobehling** [comment]
Add bottom section as below:
screenshot from 2017-07-16 14-06-38

**Comment by rishiraj824** [comment]
@mariobehling Please check I've made the changes. http://susi-overview.surge.sh
Although I couldn't add `Settings` menu as of now since it's a dialog with all functions related to the Chat Section which isn't here.

**Comment by mariobehling** [comment]
* Top bar should stay the same
* Your example on top "Hey SUSI. ... Hi I am SUSI" - apparently a bad example as this is a bug. Do you see this or not?

**Comment by mariobehling** [comment]
* Please ensure the video opens in the same way as it does on the Google Assistant page.

**Comment by mariobehling** [comment]
Add the links to the repositories into the text itself
> SUSI.AI already runs on many chat services and social networks. We are developing plugins for all major services including Twitter, Facebook, Line, Whatsapp, Viber, Slack, Gitter and Wechat. Just set up SUSI on your channel and add  @susi in your conversations and SUSI is ready to help.

screenshot from 2017-07-17 10-31-40

**Comment by mariobehling** [comment]
* Add a "safe and secure" image similar to the Google site.

**Comment by mariobehling** [comment]
* Check the bottom bar links: e.g. there is not underline and the color changes on scroll over.
* Also add the SUSI.AI logo in a similar way on the left bottom

**Comment by mariobehling** [comment]
* Make the top bar disappear on scroll down and re-appear on scroll up

**Comment by mariobehling** [comment]
Please ensure better examples on the Gif "Hello - Hello - Hi - Hello"? Please find an interesting example! We have enough, don't we?

**Comment by rishiraj824** [comment]
@mariobehling Okay, i'll make the changes. We have good examples will make gifs of those :+1:

**Comment by mariobehling** [comment]
Ensure the site works well on different resolutions and mobile.

Currently when I check different resolutions I see:
* some images are left aligned, some centered, some something else
* some images suddenly become bigger, some smaller
* text does not use the full width where it should

screenshot from 2017-07-17 10-48-08

**Comment by rishiraj824** [comment]
@mariobehling Please check now at http://susi-overview.surge.sh

**Comment by mariobehling** [comment]
* Increase the size of the video and autoplay it.

**Comment by mariobehling** [comment]
Next to "Ask it anything" it still shows a gif that shows the example of Hello, Hello, Hi, Hi..

**Comment by mariobehling** [comment]
Add buttons for stores and link these buttons to the download of Android apk and iOS ipa on our repositories.

screenshot from 2017-07-17 20-53-27

**Comment by mariobehling** [comment]
* Check the bottom bar links: e.g. there is not underline and the color changes on scroll over.
* Also add the SUSI.AI logo in a similar way on the left bottom
* Make the top bar disappear on scroll down and re-appear on scroll up (same as Google)
* Ensure the video opens in the same way as it does on the Google Assistant page. (in the same size!)
* Top bar should have the same color as chat page, but background of main content should be white
* If you give these examples "Search for the capital of Vietnam or find translations in different languages. Ask SUSI for your location, and what the weather’s like when you get there." - Then show one or two of those examples on the gif and ensure that is is a good answer. Do not show a bug in a gif!
* Make a more suitable text break. See the screenshot below to understand what I mean:
screenshot from 2017-07-17 21-02-38

**Comment by mariobehling** [comment]
@rishiraj824 Thank you. Merging this now, but I marked the points that you missed out. Please follow up on the next issue here: https://github.com/fossasia/chat.susi.ai/issues/514 and after that create a team page: https://github.com/fossasia/chat.susi.ai/issues/513.

**Pull request merged**
