### PR TITLE
Add Icons for email and password fields #1149

### PR DESCRIPTION
**Pull request by SudhanvaMG**
screenshot from 2018-03-19 01-18-47

### CODE REVIEW

**Comment by SudhanvaMG** [comment]
screenshot from 2018-03-19 01-18-47

**Comment by duttaditya18** [comment]
Can you give a preview link using Surge?

**Comment by SudhanvaMG** [comment]
Hey , i will look into it.
Havent used surge .
Will do and update it to u

**Comment by SudhanvaMG** [comment]
Link to surge
http://abrasive-eye.surge.sh/

**Comment by duttaditya18** [comment]
@SudhanvaMG Awesome!

**Comment by SudhanvaMG** [comment]
@duttaditya18  can you merge this , i have solved other issues . I wanted to create PR for those

**Comment by duttaditya18** [comment]
Ping @Orbiter

**Comment by SudhanvaMG** [comment]
@duttaditya18  due to some reason i had to create a new fork , so i will be creating a new PR for this , sorry for the inconvenience

**Pull request closed without merging**
