### PR TITLE
Solves #1989 : Aligns placeholder for password and Login button

### LINKED ISSUE #1989: Placeholder text is not aligned properly
**Actual Behaviour**

capture

**Expected Behaviour**

Placeholder text in the password field and text in Login Button should be aligned properly.

**Would you like to work on the issue?**

Yes, I would like to work on this.

### PR DESCRIPTION
**Pull request by rajshah9914**
Aligns Password placeholder..

Fixes #1989
Changes: Aligns placeholder for password.

Screenshots for the change: 
aligned_pass

### CODE REVIEW

**Comment by rajshah9914** [comment]
@AakashMallik 
Surge Link:-
http://susi_chatbot.surge.sh/
Aligned Password Field can be checked here..

**Comment by AakashMallik** [comment]
Next time onwards, make the PR title more descriptive.. @rajshah9914

**Comment by AakashMallik** [comment]
screenshot-susi_chatbot surge sh-2019 02 11-21-19-05

Login button text in not aligned... @rajshah9914

**Comment by rajshah9914** [comment]
pr 1989

Since there was no reply from the other side, I just made a small change for password alignment, if you permit, would align login too..still waiting for the response there for Login alignment..

**Comment by AakashMallik** [comment]
> pr 1989
> 
> Since there was no reply from the other side, I just made a small change for password alignment, if you permit, would align login too..still waiting for the response there for Login alignment..

Make the changes, we'll review and let you know if any changes are needed if at all they are needed.

**Comment by AakashMallik** [comment]
@rajshah9914 The text in login button is still not aligned. Don't look for quick patches, fix the cause of the error. For some reason the margin trick doesn't feel right to me.

**Comment by rajshah9914** [comment]
Ok, will try to do it soon and Thanks for your support @AakashMallik

**Comment by rajshah9914** [comment]
center_align
@AakashMallik @akshatnitd Please Review this....Thanks..

**Comment by rajshah9914** [comment]
center_align
@AakashMallik @akshatnitd sir, can you please review this..

**Pull request merged**
