### PR TITLE
Fixes: #550 - Message composer height increases when it overflows

### PR DESCRIPTION
**Pull request by isuruAb**
Fixes issue #550

Changes: Now height of message composer increases when it overflows

Demo Link: http://isuruab1.surge.sh/

Screenshot:
screen shot 2017-08-01 at 3 01 06 pm

### CODE REVIEW

**Comment by rishiraj824** [comment]
Please check for travis failures

**Comment by isuruAb** [comment]
@rishiraj824  please review again

**Comment by rishiraj824** [comment]
@isuruAb 

> Whatsapp web has 5 lines and only shows a scroll bar after that if there is more text. Please follow this approach.

I think we want 5 lines of no scroll division, then the scroll bar should appear.

**Comment by isuruAb** [comment]
@mariobehling  @rishiraj824  @uday96  @madhavrathi  Please review this.
Demo Link: http://isuruab1.surge.sh/

**Comment by mariobehling** [comment]
Thank you.

**Pull request merged**
