### PR TITLE
Fixes #641 #713 - Use same width of content across all pages

### LINKED ISSUE #641: Use same width of content across all pages
The width of the content area is different on different pages. Please ensure the distance to the left and right is the same on all pages, e.g. compare the left area on the Overview and Support page.

screenshot from 2017-07-30 14-06-00

### PR DESCRIPTION
**Pull request by isuruAb**
Fixes issue #641 #713 
Changes: 

- [x] Adjust content width of Overview page on different screen sizes 
- [x] Adjust content width of Devices page on different screen sizes 
- [x] Adjust content width of Team page on different screen sizes 
- [x] Adjust content width of Support page on different screen sizes 
- [x] Terms page ()
- [x] Contact page
- [x] Move menu items on footer next to SUSI logo like in earlier versions of page 

Demo Link: http://isuruab-res.surge.sh/overview

Screenshots for the change: 

screen shot 2017-08-05 at 8 28 05 pm

### CODE REVIEW

**Comment by mariobehling** [comment]
A number of items are no longer centered. Some images might be too big. Please ensure the indent is the same on both sides - left and right.

screenshot from 2017-08-06 23-17-37

screenshot from 2017-08-06 23-17-05

**Comment by mariobehling** [comment]
Please use the latest code that was commited from others e.g. why is the ico still a very old one?

**Comment by mariobehling** [comment]
> Move menu items on footer next to SUSI logo like in earlier versions of page

It is not fixed.

@madhavrathi Please assist as it was changed after your PR trying to fix responsiveness.

**Comment by mariobehling** [comment]
Reduce the size of pictures in order to be able to portray 4 images next to each other.

screenshot from 2017-08-06 23-25-24

**Comment by mariobehling** [comment]
Width of pages is not equal on all pages, e.g. headings on team page are further left than content on support page.

Support page also has content leaning to the right. Please ensure all pages are the same!

screenshot from 2017-08-06 23-27-11

**Comment by mariobehling** [comment]
Footer disappeared on the pages.

**Comment by isuruAb** [comment]
@mariobehling  please review this PR again  http://isuruab1.surge.sh/overview

**Comment by rishiraj824** [comment]
screenshot from 2017-08-07 19 16 18
Please check the alignment of TItle and the images below. I think you can reduce the left padding. Also maybe have 4 images per row.

**Comment by isuruAb** [comment]
@rishiraj824  we can show 4 members in a row by reducing the width but then most of the names break in to two lines

**Comment by rishiraj824** [comment]
@isuruAb Okay. Please confirm with @mariobehling once regarding this.

**Comment by uday96** [comment]
iser

Why arent the top bar logo and buttons occupying the full width? Is it expected or a bug?

**Comment by isuruAb** [comment]
@uday96  yes it is possible but i'm following this https://api.ai/ . in wider screens it shows a static width.

**Comment by mariobehling** [comment]
* Width of pages is not identical - it should be same across all pages
* Width of blog and team page is smaller than overview
* Width of support page is larger
* On teams page there should be 4 pictures next to each other. The text below the pics can be a bit smaller. The width should be matching the overview page

**Comment by mariobehling** [comment]
Why are you not using the complete new code, e.g. the ico is still the old one. This was mentioned two days ago: https://github.com/fossasia/chat.susi.ai/pull/678#issuecomment-320533505

**Comment by mariobehling** [comment]
* The footer is not correct. Please compare with earlier versions.
@madhavrathi Please provide input!

**Comment by madhavrathi** [comment]
@mariobehling I have already made the PR for fixing footer: https://github.com/fossasia/chat.susi.ai/pull/696
This PR also resolves the top bar alignment issue that was faced in chromium web browser.

**Comment by isuruAb** [comment]
@mariobehling  @madhavrathi  please review this

**Comment by isuruAb** [comment]
@sudheesh001  done those changes as requested. please check the preview link again. 👍 
http://isuruab-res.surge.sh/

**Comment by mariobehling** [comment]
Ok, thank you. I am opening a follow up issue. Cheers.

**Pull request merged**
