### PR TITLE
Fixes #994 Add Codecov report feature in .travis.yml

### LINKED ISSUE #994: Add Codecov report feature in .travis.yml
**Actual Behaviour**
Presently, There is no support of `CODECOV` report.
 
Please state here what is currently happening.

**Expected Behaviour**
Adding `CODECOV` support in travi.
State here what the feature should enable the user to do.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Would you like to work on the issue?**
**Yes, I would like to work on this issue**
Please let us know if you can work on it or the issue should be assigned to someone else.

### PR DESCRIPTION
**Pull request by bhaveshAn**
Fixes issue #994 

Changes: [Add here what changes were made in this issue and if possible provide links.]
Adding following in `.travis.yml`
```
after_success:
  - bash <(curl -s https://codecov.io/bash)
```
Demo Link: [Add here the link where your changes can be seen]

Screenshots for the change: 

@leto @rctay @anchepiece @hongquan Please review. Thanks!!

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks. Please resolve merge conflicts.

**Comment by rishiraj824** [comment]
@bhaveshAn Please resolve conflicts. Thanks!

**Comment by bhaveshAn** [comment]
Done @mariobehling Please check now

**Comment by bhaveshAn** [comment]
@rishiraj824 Can you please generate Codecov token and add it at file `codecov.yml` as you have write access to this project.
Then, this repo would be able to get CodeCov reports right at the pull requests.

Thanks !!

**Pull request merged**
