### PR TITLE
Making feedback display consistent

### LINKED ISSUE #1452: Skills Feedback not working consistently
**Actual Behaviour**

The colors of the feedback buttons changes on click, even if the response of AJAX request fails.

**Expected Behaviour**

The colors should not change, a visual clue should be given that the rating wasn't successful so that the user tries again.

**Steps to reproduce it**

On thumbs up or thumbs down click, check the console. Even the ajax response leading to error will change the colors of the button.

**Screenshots of the issue**

image

**Would you like to work on the issue?**

YES

### PR DESCRIPTION
**Pull request by thakursaurabh1998**
Fixes #1452 

Changes: The feedback buttons(thumbs up and down) doesn't change colors until there is a successful ajax call returned. Additionally a toast or any other message format can be added to tell the user that the feedback wasn't successful.

Demo Link: https://pr-1454-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by thakursaurabh1998** [comment]
@AnupKumarPanwar any leads?

**Comment by AnupKumarPanwar** [comment]
@thakursaurabh1998 I'm sure if this will have a good effect on the UX, as on slow connections the user might think that the thumbs are not functional.

**Comment by thakursaurabh1998** [comment]
A message can be displayed. I can add it. Is there any pre-built snackbar or toast or can I show my custom mesaage? @AnupKumarPanwar

**Comment by thakursaurabh1998** [comment]
@mariobehling Yes, thank you for the idea I will implement it ASAP.

**Comment by thakursaurabh1998** [comment]
This issue is free to take for anybody.

**Pull request closed without merging**
