### PR TITLE
Solve header bar issue in dark theme in settings

### LINKED ISSUE #1025: Header bar in settings doesn't become dark completely after changing theme to dark
**Actual Behaviour**
The header bar in settings doesn't become dark completely after changing the theme from "light" to "dark".
screen shot 2018-01-10 at 10 28 30 pm

**Expected Behaviour**

The whole header bar should become dark.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by DNS-404**
Fixes #1025 

Changes: Added dark theme style in header of settings.

Screenshots for the change: 

Before-
screen shot 2018-01-10 at 10 28 30 pm

After-
screen shot 2018-01-10 at 10 33 09 pm

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
It looks good but a deployment will be appreciated 😅

**Comment by DNS-404** [comment]
Sure! Here it is - http://lovely-comfort.surge.sh/

**Comment by DNS-404** [comment]
@aashutoshrathi @nileshgulia1 Please review.

**Comment by DNS-404** [comment]
@madhavrathi Please Merge

**Pull request merged**
