### PR TITLE
Update INSTALLATION_SURGE.md (Solving Issue #972)

### PR DESCRIPTION
**Pull request by kartikeya23**
Improving documentation 
Arranging everything in the correct order

Demo Link: https://github.com/kartikeya23/chat.susi.ai/blob/master/docs/INSTALLATION_SURGE.md

Screenshots of the change: 
screenshot from 2017-12-27 10-27-06

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
Resolve conflicts

**Comment by mariobehling** [comment]
Thanks! Please finalize by resolving conflicts.

**Comment by rishiraj824** [comment]
@kartikeya23 Please fix conflicts.

**Comment by duttaditya18** [comment]
@kartikeya23 Please resolve merge conflicts please!

**Comment by isuruAb** [comment]
please resolve the conflicts

**Comment by akshatnitd** [comment]
@kartikeya23 Please resolve the conflicts. It is ready to merge!

**Comment by mariobehling** [comment]
Thanks. Please resolve merge conflicts.

**Comment by mariobehling** [comment]
Closing it due to inactivity.

**Pull request closed without merging**
