### PR TITLE
Upgrade react to 16.4, material ui to 0.20.1 #1464

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #1479 

Changes: 

1. Upgrade to React v16.4 and React-dom to v16.4
2. onTouchTap replaced by onClick
3. html-react-parser upgraded(older version had issue)
4. material-ui-responsive-menu, material-ui-scrollable-tabs were not being used anywhere.
5. Removed react-tap-event-plugin (injectTapEventPlugin)
6. Upgrade to newer material-ui@0.20.1

Demo Link: https://pr-2078-1-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by fragm3** [comment]
@akshatnitd Yes, material UI will be upgraded to >3 version. We need this version of material UI for working of onClick instead of onTouchTap. Upper versions are quite drastic changes in API, which will be done in subsequent PR's. I had tried solving these Travis errors back in the time. I tried everything, couldn't find a way to solve them.

**Comment by fragm3** [comment]
@akshatnitd I have deleted the tests for the error files. I have tried many times to solve those errors.

**Comment by fragm3** [comment]
Errors:
Screenshot 2019-05-08 at 2 18 15 PM

**Comment by akshatnitd** [comment]
Also, if you don't have permissions to deploy to a link, manually deploy it to a surge link via surge CLI.

**Comment by fragm3** [comment]
> Deleting the test files are not a solution and shouldn't be done. Please look out for a concrete fix.

@akshatnitd I have tried every possible solution to fix those errors. That too multiple time.

**Comment by fragm3** [comment]
@akshatnitd please review

**Comment by fragm3** [comment]
@akshatnitd I have sent a screenshot of Travis errors due to those files. I had tried fixing those error, scrounged the net for hours, tried every possible solution, still could not get the errors working. If you or @harsh-jindal want to try fixing those error or find a solution. 
PS: I used npm package`trevor` for running Travis test locally.

**Comment by akshatnitd** [comment]
Okay, I ll pull your branch and test.

**Comment by fragm3** [comment]
@akshatnitd For `VoicePlayer`, `VoiceRecognition`, I tried using refs inside these, just for trying. But it's not working. The problem is enzyme will never be able to find addEventListener in this.`speech`.addEventListener. We need to have a newer implementation for these 2 files, setting state instead of addEventListener. For the time being, I am quite focused on shifting codebase to a newer material ui. Once we have shifted to the new version of material ui. I will state with the newer implementation of `VoicePlayer`,`VoiceRecognition`

**Comment by fragm3** [comment]
@akshatnitd I have removed all the refs inside `RemoveDeviceDialog.js` as they were not needed. Added the test for same.

**Comment by fragm3** [comment]
@akshatnitd, please review

**Comment by fragm3** [comment]
@akshatnitd Sure thing

**Pull request merged**
