### PR TITLE
fix css bugs in ChatApp.css

### LINKED ISSUE #1793: css bugs in text field in ChatApp
**Actual Behaviour**

In firefox quantum(63)
- text being typed isnt visible

**Expected Behaviour**

this shoud be fixed

**Steps to reproduce it**

open chat.ssui.ai in firefox quantum

**Screenshots of the issue**

susiscreenshot

**Would you like to work on the issue?**

work done!! just going to open a PR

### PR DESCRIPTION
**Pull request by ammarbinfaisal**
Fixes #1793 

Demo Link: https://pr-1794-fossasia-susi-web-chat.surge.sh

**Aim**
make the text in the textarea visible on firefox(<63)

Screenshots for the change: 
susiscreenshot

### CODE REVIEW

**Comment by AakashMallik** [comment]
@ammarbinfaisal That is not a black area, those are scroll buttons. Shouldn't have removed it.

**Comment by ammarbinfaisal** [comment]
@AakashMallik 
yeah I know that. that was initially perceived to be so.
but why would anyone need to scroll a textarea?

**Comment by AakashMallik** [comment]
@ammarbinfaisal Paste this in your text area. 
```
The explanation for this question can take a while, I'll let you know the answer later.Hfdsifadsfffffffffffffffffffffffdafds fdsafafds fasdfj;alsfja;fjd;slakjflkajsf;lsajf;ldsja;fl
```

**Comment by ammarbinfaisal** [comment]
### after pasting in textfield of chat.susi.ai
susi

### pasting in my fork
susi

**Comment by ammarbinfaisal** [comment]
the default color for input tag would be #fff in firefox(63) and this is why it is happening

**Comment by AakashMallik** [comment]
@ammarbinfaisal My point was at some message length **l** you would need to do a vertical scroll. How will you cover that?

**Comment by ammarbinfaisal** [comment]
oh, sorry!!
didnt think about that.
you could have said that directly. so I am changing the issue description and my Pr commit

**Comment by ammarbinfaisal** [comment]
@samagragupta done sir

**Pull request merged**
