### PR TITLE
Fixes: #514 - Improve overview page

### PR DESCRIPTION
**Pull request by isuruAb**
Fixes issue #514

Changes: 

- [x]  Move SUSI.AI logo to the top left on Overview page and add menu items "Overview", "Docs", "Blog", "Team" (Don't do this on the chat service top bar though.)
- [x]  Scroll over on "Watch" does not indicate it is a link
- [x] Check the functionality of the Top Bar of the Google assistant landing page again. Scroll up and down. Stop somewhere and scroll up or down again. Also check the behavior when you start to scroll. Configure the SUSI top bar to work similarly.

- [x] Check the bottom bar links: e.g. there is not underline and the color changes on scroll over.
- [x] Ensure more white space above bottom bar (and below the security bar! - in between. Compare to Google!)

- [x] Increase the size of the bottom bar to match Google

- [x] In section "For all Devices": Increase the space below the text (and in front of the buttons) and rename section to "For your Smartphone"

- [x] Add logo of Open Source Initiative in the section "SUSI is Open Source" and the Github (word logo with link to https://github.com/fossasia?utf8=✓&q=susi)

- [x] Add an area with three columns similar to api.ai. The sections should be

- On many Platforms (convert the area - "Integrate SUSI with your favorite chat services and social networks." - to this section)
- For all Devices
- Use it in many Languages   

Demo Link: http://isuruab2.surge.sh/overview

Screenshots for the change: 
screen shot 2017-07-19 at 9 41 38 am

screen shot 2017-07-19 at 1 10 46 pm

### CODE REVIEW

**Comment by rishiraj824** [comment]
@isuruAb we can reduce the left and right spacing in the image which is causing the left and right white space around it. Here's the screenshot. 
screenshot from 2017-07-19 20 40 33
The alignment can also be improved.
screenshot from 2017-07-19 20 41 26

**Comment by isuruAb** [comment]
@rishiraj824  please review it again please

**Comment by rishiraj824** [comment]
The SUSI logo and the links overlap on phones. Please check that.

**Comment by rishiraj824** [comment]
Center the open source logo on phones like the other images

**Comment by isuruAb** [comment]
@rishiraj824  please check this again

**Comment by rishiraj824** [comment]
isuruab2 surge sh-overview nexus 5
The menu still needs to be fixed. Rest looks good.

**Comment by daminisatya** [comment]
Looks clean :D

**Comment by mariobehling** [comment]
Thanks!

**Pull request merged**
