### PR TITLE
Linking SUSI logo to Index page

### LINKED ISSUE #1196: The Main SUSI LOGO is not hyperlinked to anything when on the chat page
**Actual Behaviour**

Clicking the SUSI LOGO does not do anything 

**Expected Behaviour**

To refresh the page

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by prateekiiest**
Fixes #1196 

Changes: 
The SUSI logo now points to the about page

### CODE REVIEW

**Comment by isuruAb** [comment]
@prateekiiest  please send a demo URL with your PRs. It makes the review process easy.

**Comment by AnupKumarPanwar** [comment]
@Akshat-Jain  @anshumanv , I agree with your view.

**Comment by prateekiiest** [comment]
when I am deploying to surge with a given domain name, the page does not get published and I end up with page not found error. Some problem in the index.html file?

**Comment by anshumanv** [comment]
In the current version, the logo already redirects to the index page.

**Comment by prateekiiest** [comment]
@anshumanv I have made the changes. Are you referring to the original site  https://chat.susi.ai/?

**Comment by anshumanv** [comment]
> @anshumanv I have made the changes. Are you referring to the original site https://chat.susi.ai/?

Yes, it works for me at least.

**Comment by prateekiiest** [comment]
@anshumanv when you are chatting with SUSI in the chat.susi.ai,
try clicking on the logo. it will not work.

If you are in the about section, then it will work only

**Comment by prateekiiest** [comment]
Made the changes. Any additional that needs to be done?

**Comment by mariobehling** [comment]
@prateekiiest Please provide a test page, e.g. on surge. Thanks.

**Comment by prateekiiest** [comment]
Deployed URL http://ready-drink.surge.sh/

**Comment by mariobehling** [comment]
Thanks!

**Pull request merged**
