### PR TITLE
Add show/hide toogle to chats

### LINKED ISSUE #1186: Implement option to clear chat history
**Actual Behaviour**
Whenever we open the webchat it just shown the previous chats.

**Expected Behaviour**
But if you see assistants like siri etc they did not show them directly.

- We can make a show hide toogle button.
- For clearing history we can give options like clear history for the past hour, day etc.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by PrP-11**
Fixes #1186 

Changes: Add an option to Show/hide chats

Demo Link: http://fantastic-experience.surge.sh/

Screenshots for the change: 
hide

show

### CODE REVIEW

**Comment by Akshat-Jain** [comment]
Looks good!
Fix the Travis failure though :-)

**Comment by PrP-11** [comment]
@hkedia321 I added the show icon and for the font size, I set it to 16px now, earlier I increased it to differentiate it  from the size of hide ,is it okay now!

show

 and @anshumanv I changes the states names and the indentations are correct if you see the actual code from the file:

indentation
but on github it is shown as : 
indentation1

I don't know why it is showing different from the original file

**Comment by PrP-11** [comment]
@Akshat-Jain I am already working on implementing this on all action types, currently its only available for chats :smile:

**Comment by mariobehling** [comment]
Please relate to my comment here: https://github.com/fossasia/chat.susi.ai/issues/1186#issuecomment-390087125

**Pull request closed without merging**
