### PR TITLE
Fixed #975: Fixed Sidebar Overflowing

### LINKED ISSUE #975: Settings sidebar overflows
**Actual Behaviour**

Sidebar of the settings page overflows from items.

**Expected Behaviour**

Settings list should be fit to the sidebar

**Screenshots of the issue**

screen shot 2017-12-29 at 6 33 21 am

**Would you like to work on the issue?**

anyone can get it

### PR DESCRIPTION
**Pull request by naveentherocker**
Fixes #975 

Changes
- Fixed Sidebar Overflowing in the bottom

### CODE REVIEW

**Comment by daminisatya** [comment]
screen shot 1939-10-08 at 11 50 47 am

**Comment by naveentherocker** [comment]
@daminisatya Now I fixed the Travis Build.

**Comment by mariobehling** [comment]
@naveentherocker Have a test link?

**Comment by rishiraj824** [comment]
@naveentherocker Please squash your commits. Thanks!

**Pull request merged**
