### PR TITLE
Fixes #835 : Theme changes doesn't change Mic icon

### LINKED ISSUE #835: mic disappears when theme is changed from  drop down menu at top of right .
**Actual Behaviour**

Mic disappears when theme is changed from drop down menu at top of right.

**Expected Behaviour**

Mic must not disappear until we start typing message.

**Steps to reproduce it**
       1. Log in
       2. Change theme from drop down menu at top of right
    
**Screenshots of the issue**
mic

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes issue #835 

Changes: 
* Make correction in the state name that was responsible for setting the theme name
* Send correct key name to the request to the Server. It was incorrectly sent as **Theme**, instead of **theme**.

[Demo Link](http://cooperative-twist.surge.sh)

Screenshots for the change: 
sscreen

### CODE REVIEW

**Comment by RMCoder198** [comment]
@akshatnitd   
These are mentors @madhavrathi  @isuruAb .They will merge your pull request.

**Comment by akshatnitd** [comment]
@RMCoder198 Okay. @madhavrathi @isuruAb Please review :)

**Comment by akshatnitd** [comment]
@isuruAb Made the correction

**Comment by rishiraj824** [comment]
@akshatnitd Please also make sure it works in both logged-in, and in the anonymous state.

**Comment by akshatnitd** [comment]
@isuruAb @madhavrathi Made the requested changes and updated the demo link.

**Comment by mariobehling** [comment]
Thank you.

**Pull request merged**
