### PR TITLE
Remove JQuery from DOM manipulation

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Initial workarounds for #1725

Made couple of workarounds within the ``` RemoveDeviceDialog.react.js ``` file removing JQuery from manipulating the DOM.

Demo link available at [surge](http://smoggy-duck.surge.sh/)

### CODE REVIEW

**Comment by AakashMallik** [comment]
Could you paste a preview link @jamesgeorge007 so that I can see if it is working.

**Comment by AakashMallik** [comment]
And again @jamesgeorge007 squash those commits.

**Comment by jamesgeorge007** [comment]
My working tree is becoming dirty while squashing them into a single commit. What about the squash and merge option?

**Comment by AakashMallik** [comment]
@jamesgeorge007 Could you describe the steps you are taking in order to squash the commits? Maybe I could suggest something here.

**Comment by jamesgeorge007** [comment]
I did ```git rebase -i origin/master```  for the squashing purpose.

**Comment by AakashMallik** [comment]
> I did `git rebase -i origin/master` for the squashing purpose.

origin/master? It would have been easier to do it against upstream/master

**Comment by jamesgeorge007** [comment]
@AakashMallik What do you think now?

**Comment by AakashMallik** [comment]
> @AakashMallik What do you think now?

Commit message should be a bit more descriptive than "workarounds :+1:". Other than that, I guess things look fine to me.

**Comment by jamesgeorge007** [comment]
Is anything going wrong here?
> couple of lines highlighted in `dark red` within the PR diff

**Comment by AakashMallik** [comment]
@jamesgeorge007 It says EOF missing. See if you can fix that.

**Comment by AakashMallik** [comment]
Also for CI, try reopening the issue. For some reason, the build did not start.

**Comment by jamesgeorge007** [comment]
@AakashMallik CI build passed 👍

**Pull request merged**
