### PR TITLE
Keep bottom text field onClick search button

### PR DESCRIPTION
**Pull request by nileshgulia1**
fix for issue #823  
screenshot from 2017-10-01 18-28-34

### CODE REVIEW

**Comment by RMCoder198** [comment]
Add A demo link so we can see your work and screenshot too.

**Comment by nileshgulia1** [comment]
Hello @madhavrathi, Here's a demo link https://blooming-sands-63650.herokuapp.com/

**Comment by RMCoder198** [comment]
@nileshgulia1 
Search function  is not working in your demo link.
search1

**Comment by RMCoder198** [comment]
@nileshgulia1 
I am working on this issue before you .So whenever you start work on issue ,you should check if someone else is working  on that issue or not.
Well ,i am also facing few problems.So if you fix this issue you can make pull request.

**Comment by RMCoder198** [comment]
An i am still working on this issue.So we both can work on this issue.

**Comment by nileshgulia1** [comment]
Hello @RMCoder198 .It seems you were not assigned the issue, this make me work on this issue . it doesn't matter actually anyways, I will figure it out what the new issue is and sure we can fix it.

**Pull request closed without merging**
