### PR TITLE
Improves UI of Login Popup.

### PR DESCRIPTION
**Pull request by saurabh30**
Fixes issue #882

Changes: Placed login and sign up side by side.

Demo Link:  [http://hanging-purpose.surge.sh/](http://hanging-purpose.surge.sh/)

Screenshots for the change: 
image

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
@saurabh30 Patch is fine, just fix the Travis issues.
```
295:1  error  Trailing spaces not allowed          no-trailing-spaces
  295:1  error  More than 2 blank lines not allowed  no-multiple-empty-lines
  296:1  error  Trailing spaces not allowed          no-trailing-spaces
  297:1  error  Trailing spaces not allowed          no-trailing-spaces
```

**Comment by saurabh30** [comment]
@aashutoshrathi @isuruAb @anshumanv  fixed travis.Plz review.

**Comment by anshumanv** [comment]
Didn't work when I checked, no issues. :+1:

**Comment by saurabh30** [comment]
@anshumanv There was some problem on c9.Thanks for telling.Updated the demo link by deploying on surge.

**Comment by anshumanv** [comment]
@saurabh30 awesome! :smile:

**Pull request merged**
