### PR TITLE
Modified the Background colour in Dark theme

### LINKED ISSUE #1142: Dark Theme Modifications
**Actual Behaviour**

The present dark theme is good. But we use Dark theme when working in low light or to save the battery Power and in present dark theme we have white background which is consuming more power and on the chat screen text is in greenish color which is readable but gives strain on eyes.

**Expected Behaviour**

1.Background color should be changed.
2.Text Color in Dark theme should be changed.

**Screenshots of the issue**

before dark theme chat

before settings dark theme

**Would you like to work on the issue?**

Yes!

### PR DESCRIPTION
**Pull request by singhrohan62**
Fixes #1142 

Changes: [Add here what changes were made in this issue and if possible provide links.]

Demo Link: https://pr-[ADD_PULL_REQUEST_NUMBER_HERE]-fossasia-susi-web-chat.surge.sh

Screenshots for the change:

### CODE REVIEW

**Comment by psikarwal** [comment]
@singhrohan62 update the surge deployment link as well.

**Comment by singhrohan62** [comment]
@psikarwal light theme mode does'nt have dark background. Here are the screenshots of the application in light and dark theme : 
screenshot 54


screenshot 53

**Comment by psikarwal** [comment]
@singhrohan62, go to Settings Menu and check once. 😜
pull_1169

**Comment by singhrohan62** [comment]
I thought that our main focus was on providing dark background colour to chat section 😊 . I am working on this and will soon update the code.

**Pull request closed without merging**
