### PR TITLE
refactored MapContainer

### LINKED ISSUE #1718: Refactor MapContainer
**Actual Behaviour**

MapContainer needs to be refactored.

**Expected Behaviour**

Refactored MapContainer to make it consistent with codebase

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by sunitasen**
Fixes #1718 

Changes: 

- ordered import statement
- moved style out of components

Demo Link: https://pr-1721-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by sunitasen** [comment]
done. @AakashMallik :smile:

**Comment by AakashMallik** [comment]
@sunitasen squash the commits, please.

**Comment by sunitasen** [comment]
@AakashMallik I tried squashing the second commit but it didn't appear in the 'rebase' commit. 
Secondly, I tried locally updating my branch and then squashing the commits, it resulted into changes in 32 files in a single commit. :laughing: . I had a hard time rolling it back.
Any suggestions?

**Comment by sunitasen** [comment]
@AakashMallik  done.

**Pull request merged**
