### PR TITLE
Removed duplicate code on signup.react.js

### LINKED ISSUE #1654: Duplicate code in SignUp.react.js
**Actual Behaviour**

Same code is written two times in different ways.

**Expected Behaviour**

Redundancy/Duplicacy should be resolved.

**Steps to reproduce it**

https://github.com/fossasia/chat.susi.ai/blob/master/src/components/Auth/SignUp/SignUp.react.js

At line 176 and 212.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #1654 

Changes: Redundancy/Duplicacy is resolved.

Demo Link: https://pr-1655-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by AakashMallik** [comment]
@samagragupta Squash your commits, please.

**Comment by samagragupta** [comment]
@AakashMallik `Merge branch 'master' into duplicate-signup` These commits cannot be squashed.

**Comment by samagragupta** [comment]
@AakashMallik `Merge branch 'master' into duplicate-signup` These commits cannot be squashed.

**Comment by AakashMallik** [comment]
@samagragupta You should have rebased it with the master instead of merging.

**Comment by AakashMallik** [comment]
```
(on branch - master)
git fetch upstream
git rebase -i upstream/master
git checkout duplicate-signup
git rebase -i master

git push origin duplicate-signup --force
```

**Pull request merged**
