### PR TITLE
Fixes #677 Added separate component for footer

### LINKED ISSUE #677: Make separate component for FOOTER
**Actual Behaviour**

Footer code is being repeated in every static page.

**Expected Behaviour**

We should make a separate component for it.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by madhavrathi**
Fixes issue #677

Changes: Added the previous footer and made a separate component for it
Next steps:

- [x] Fix footer on blog page
- [x] Fix footer for 300px resoultion

Demo Link: http://magenta-effect.surge.sh/overview

Screenshots for the change: 
for screen width (1366px wide):

for screen width < 800px : 

for screen width < 300px: 

@rishiraj824 @uday96 @isuruAb Please review
Thanks

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks.

**Comment by mariobehling** [comment]
@madhavrathi Further testing the footer, it is not working as expected. In small resolutions the footer disappears completely. Also see below. The logo and menu items are not aligned anymore.

screenshot from 2017-08-11 19-30-03

**Comment by madhavrathi** [comment]
@mariobehling this must be due to recent merge of same width PR.I tested footer for resolutions and it worked fine. I will look into the issue and will update here.

**Comment by mariobehling** [comment]
Please follow up here: https://github.com/fossasia/chat.susi.ai/issues/725

**Pull request merged**
