### PR TITLE
Fixes #1034. Add a scrollbar library for message composer and make message composer opaque.

### LINKED ISSUE #1034: Multiple Issues with message composer.
**Actual Behaviour**
Message composer is transparent and overlaps with bottom part of message list in dark theme mode.
Message composer is opaque and hides bottom part of message list in light theme mode.
Message composer scrollbar is completely white when browsing using mozilla firefox (no issue with chrome or chromium)

**Expected Behaviour**
Message composer should be opaque, should not hide bottom part of message list and it's scrollbar should have the same behaviour as:
image

**Screenshots of the issue**
image

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by kapillamba4**
Fixes #1034 

Changes: Added perfect-scrollbar library and used it to replaced default message-composer scrollbar. Also changed color and transparency of message-composer for dark theme.

Demo Link: [pr-1035-fossasia-susi-web-chat.surge.sh](https://pr-1035-fossasia-susi-web-chat.surge.sh)

Screenshots for the change: 
image

### CODE REVIEW

**Comment by kapillamba4** [comment]
@isuruAb are you getting the normal horizontal scrollbar or horizontal scrollbar from the library ?

**Comment by kapillamba4** [comment]
@isuruAb, i am not able to reproduce the issue. Can you please provide more information?

**Comment by isuruAb** [comment]
here it is. It shows when user scrolls the message content.
screen shot 2018-01-24 at 1 26 27 pm

**Comment by kapillamba4** [comment]
Travis fix PR: #1072

**Comment by mariobehling** [comment]
Closing this due to inactivity.

**Comment by kapillamba4** [comment]
Scrollbar Library does not seem to work with current chat.susi.ai, will open another PR for this soon

**Pull request closed without merging**
