### PR TITLE
Fixes #655 - Resized SUSI AI logo and used only light theme for static pages

### LINKED ISSUE #655: Increase size of logo on landing page and prevent dark theme on static pages
**Actual Behaviour**

 The current logo is too small compared to previous one on landing page top bar
 Static pages must have only light theme

**Expected Behaviour**

 Increase size of logo on top bar
 The static pages body must be only light themed

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by uday96**
Fixes issue #655 

**Changes:**
 - Resized SUSI AI logo on landing page and aligned it to left similar to static pages
 - Made document body white for static pages

**Demo Link:** http://udaytheja1.surge.sh/

**Screenshots for the change:** 

susiai

### CODE REVIEW

**Comment by uday96** [comment]
@rishiraj824 @isuruAb @madhavrathi please review

**Comment by rishiraj824** [comment]
@uday96 @madhavrathi I'm not sure about the left alignment of the logo on the chat page, please confirm once.

**Comment by mariobehling** [comment]
Does not load.
screenshot from 2017-08-01 18-22-25

**Comment by mariobehling** [comment]
Ok, let's see.

**Pull request merged**
