### PR TITLE
Fixed #977 - Add a video about deploy on surge in README.md, Fixed some issues on INSTALLATION_SURGE file, Translate INSTALLATION_SURGE to SINHALA.

### LINKED ISSUE #977: Improve documents
**Improvement**
Improve documents

**Expected Behaviour**

- [x] Add a video about deploy on surge in README.md.
- [x] Fixed some issues on INSTALLATION_SURGE file
- [x] Translate INSTALLATION_SURGE to SINHALA"

**Would you like to work on the issue?**

I'm working!

### PR DESCRIPTION
**Pull request by STEdirisuriya**
Add a video about deploy on surge in README.md. 
Fixed some issues on INSTALLATION_SURGE file,
Translate INSTALLATION_SURGE to SINHALA.

Fixes issue https://github.com/fossasia/chat.susi.ai/issues/977

Changes: [Add here what changes were made in this issue and if possible provide links.]
https://github.com/STEdirisuriya/chat.susi.ai/commit/179180381a37d93796c983d0a1961be5d23ad19c

Demo Link: [Add here the link where your changes can be seen]
https://github.com/STEdirisuriya/chat.susi.ai

### CODE REVIEW

**Comment by gabru-md** [comment]
Please change the PR to `Fixes #issue` then followed by the message. And adhere to the best practices because you have been contributing for long enough now.

**Comment by vaibhavsingh97** [comment]
@STEdirisuriya Before asking for review again please iterate what maintainer/mentor had asked. Thanks

**Comment by harshit98** [comment]
@STEdirisuriya The PR name is still not meaningful.

**Comment by duttaditya18** [comment]
Finally!

**Pull request merged**
