### PR TITLE
Fixes #237 - Fixing the carousel overlay to access know more anchor

### LINKED ISSUE #237: Carousel overlay preventing from accessing Know More hyperlink in websearch rss tiles
**Actual Behaviour**

The current carousel overlay for websearch rss tiles, is preventing from accessing the `Know more` link text in the tile, especially when used in mobile.

**Expected Behaviour**

The carousel overlay must not hinder the `Know more` anchor in the tile

**Steps to reproduce it**

Open SUSI WebChat in your mobile phone and do a websearch or rss type query
Ex: search for *

Try tapping on the `Know More` anchor in the tile, the overlay prevents the user from tapping on the anchor text.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by uday96**
Fixes issue #237 

**Changes:**
Aligned the indicator dots to the bottom so that the `Know More` tag is accessible for tap

**Demo Link:** http://tilescss.surge.sh/

**Screenshots for the change:** 

screenshot from 2017-06-14 19 25 00

PS : I think we need to create an issue for making the UI similar to android and iOS for websearch rss responses. I tried a lot of modules including 
* [react-swipe](https://github.com/voronianski/react-swipe)
* [nuka-carousel](https://github.com/FormidableLabs/nuka-carousel)
* [react-slick](https://github.com/akiran/react-slick)

But faced issues with all of them, so I ended up using the current [react-responsive-carousel](https://github.com/leandrowd/react-responsive-carousel) module

### CODE REVIEW

**Comment by uday96** [comment]
@rishiraj824 @isuruAb @madhavrathi please review.

**Comment by uday96** [comment]
@daminisatya yes, but for few responses it slightly over lies on the text. is it fine?

**Comment by daminisatya** [comment]
@uday96 Try to reduce the text width and leave some room for the arrows to occupy. This should fix.

**Comment by uday96** [comment]
@daminisatya please review it again, updated it 

arrows

**Pull request merged**
