### PR TITLE
Fixes #266 - Accounting with custom server

### LINKED ISSUE #266: Imeplement signup and forgot password with custom server
**Actual Behaviour**

No option for signup and forgot password for custom server

**Expected Behaviour**

Option to signup and reset password using custom server too

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by uday96**
Fixes issue #266 

**Changes:**

* Added custom server option in signup and forgot password

**Demo Link:** http://customserver.surge.sh/

**Sample Custom Server URL :** http://104.197.146.27

**Screenshots:** 

signup

forgot

### CODE REVIEW

**Comment by uday96** [comment]
@rishiraj824 @isuruAb @madavrathi @daminisatya Please review

**Comment by uday96** [comment]
As of now, the endpoints format is :

**default url** : http://api.susi.ai
**custom server url example** :  http://104.197.146.27

**BASE_URL** = deafult url OR custom server url 
* Server call endpoint : `BASE_URL+'/susi/chat.json?q=QUERY'`
* Login endpoint: `BASE_URL+'/aaa/login.json?type=access-token&login=EMAIL&password=PASSWORD';`
* SignUp endpoint: `BASE_URL+'/aaa/signup.json?signup=EMAIL&password=PASSWORD;`
* ResetPassword endpoint: `BASE_URL+'/aaa/recoverpassword.json?forgotemail=EMAIL'`

**Comment by uday96** [comment]
@madhavrathi Made the changes, please check again :+1:

**Comment by madhavrathi** [comment]
@uday96 great 👍

**Pull request merged**
