### PR TITLE
Fixes #154: Create a Login Page

### LINKED ISSUE #154: Create a static landing page for login
**Actual Behaviour**

No login page for testing, #144. To begin with the login feature we need to have the landing page first.

**Expected Behaviour**

This page can be routed to a static route for testing purposes, example `/login` with the ability to switch to sign up, forgot password

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by rishiraj824**
Fixes issue #154 

Changes: 
- Routed Login Screen
- Static Login Page

Demo Link: 
Go to right most vertical dot icon and click Login
http://susi.surge.sh

@uday96 @isuruAb @madhavrathi Please review and suggest changes

### CODE REVIEW

**Comment by uday96** [comment]
Wouldn't it be better if Signup and forgot password buttons are also present on the login page? Or we could add them once the signup & forgot passwords functionalities have also been implemented.

**Comment by rishiraj824** [comment]
Should I add it now or once they are implemented ? @uday96

**Comment by uday96** [comment]
Better add it so that we can simply link them once the functionalities have been implemented. :+1:

**Comment by rishiraj824** [comment]
Okay sure :+1:

**Pull request merged**
