### PR TITLE
Make forgot password form consistent with susi skill cms

### LINKED ISSUE #1485: Make Forgot Password component consistent with CMS
Actual Behaviour
* It has a different UI
No loading state for button.
Expected Behaviour
* Make Forgot Password component consistent with CMS

**Screenshots of the issue**
deepinscreenshot_select-area_20180729190034

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by rupav**
Fixes #1485 

Changes: [Made the loading icon work similar to susi skill CMS in forgot password form.]

Demo Link: https://pr-1556-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by rupav** [comment]
@akshatnitd not able to deploy on surge, followed the instructions of Readme, I am not getting any prompt for `password`, although I get a domain name, but the link has no project on it.

**Comment by rupav** [comment]
CMS doesn't have login button in forgot password form, I think we should remove it from this form also.

**Comment by rupav** [comment]
Done, removed login button, makes the modal close to susi skills form. @akshatnitd

**Comment by rupav** [comment]
updates: http://powerful-dock.surge.sh/

**Comment by rupav** [comment]
Ok will implement it 👍, need some time with CSS, as both have different styling.

**Comment by rupav** [comment]
Done, applied same margin of Reset button as of `skills.susi.ai`. Please review @fragm3 @akshatnitd .
link:  milky-breakfast.surge.sh

**Comment by rupav** [comment]
@fragm3 please review

**Comment by neeraj3029** [comment]
Just squash the commits :)

**Comment by anshumanv** [comment]
Hey @rupav, great work here! :rocket:

**Comment by rupav** [comment]
Squashed and updated @anshumanv .

**Pull request merged**
