### PR TITLE
Added blog page

### PR DESCRIPTION
**Pull request by madhavrathi**
Fixes issue #586 

Changes: Added cards for all the latest blogs in the feed.

Demo Link: http://susi-madhav.surge.sh/blog

Next Steps : 

- [x] Add featured image to every post
- [x] Add styling to every card
- [x] Add published date on every card
- [x] Add footer to blog page

Screenshots for the change: 
blogh

### CODE REVIEW

**Comment by madhavrathi** [comment]
@mariobehling It looks like the option to show featured images in our feed is disabled in settings. Can you please look into it. 
feed_issue

**Comment by mariobehling** [comment]
Ok, I activated the featured image. Please check.

**Comment by mariobehling** [comment]
Please change:
* "Blogs Latest Blogs on SUSI.AI" to "Blog Latest Blog Posts on SUSI.AI"

**Comment by madhavrathi** [comment]
@rishiraj824 @uday96 @isuruAb please review.
Thanks

**Comment by mariobehling** [comment]
The height of the original images on the blog is different, but the width is always the same. The way you are scaling images on the page here results in the distortion of some images.

**Comment by mariobehling** [comment]
Please show 10 posts per page and subsquent posts on following pages.

**Comment by mariobehling** [comment]
Do you see that some images are not scaled correctly? They are out of proportion.

screenshot from 2017-08-06 09-51-50

**Comment by madhavrathi** [comment]
@mariobehling @rishiraj824 @uday96 @isuruAb Please check the images on cards. I have fixed the distortion and each card is now of similar size. http://susi-madhav.surge.sh/blog
Thanks

**Comment by mariobehling** [comment]
Thanks!

**Pull request merged**
