### PR TITLE
 Fixes #899, Added a 'back to login' button to the ForgotPassword dialog

### LINKED ISSUE #899: Add Back button to forgot password window
**Actual Behaviour**

Once you click forgot password, there is no going back (Screenshot)

**Expected Behaviour**

Add a back button which leads back to login menu from forgot password panel

**Steps to reproduce it**

Add a back button and give it form link

**Screenshots of the issue**

fg-bug

**Would you like to work on the issue?**

No

### PR DESCRIPTION
**Pull request by anshumanv**
Fixes #899 

Changes: Added a back to login button on the ForgotPassword dialog.

Demo Link: [here](https://poor-friends.surge.sh)

Screenshots for the change: 
selection_002

### CODE REVIEW

**Comment by anshumanv** [comment]
Fixing log

**Comment by anshumanv** [comment]
Hey @isuruAb, I think you meant to tag me there.
I've given the deployment link btw, still here you go - https://poor-friends.surge.sh/

**Comment by anshumanv** [comment]
Thanks for reviewing @isuruAb :smile:

**Comment by aashutoshrathi** [comment]
@anshumanv LGTM, but wouldn't it have been nice, if we have placed a back arrow button on left top end rather than using a button. 😄

**Comment by anshumanv** [comment]
I followed up the same practice as the sign-up dialog, in order to keep things uniform. @aashutoshrathi

**Comment by aashutoshrathi** [comment]
Rebase again @anshumanv

**Comment by aashutoshrathi** [comment]
Better squash all 3 commits.

**Comment by anshumanv** [comment]
Already squashed @aashutoshrathi :-1:

**Comment by aashutoshrathi** [comment]
@anshumanv you can't erase everything 😉 
image

**Pull request merged**
