### PR TITLE
Fixes #939; translation bugs have been completely fixed

### LINKED ISSUE #939: Translation is being done of a few phrases only
**Actual Behaviour**

The translation of only a few phrases is being done, on changing the language in Settings. Basically, the JSON used for translation is incomplete, and hence a lot of the phrases are not getting translated. Since the JSONs for all the languages use the same fields, this error has propagated to the other languages too.

**Expected Behaviour**

All of the phrases should be translated appropriately.

**Steps to reproduce it**

There are many such phrases which haven't been translated properly. A few examples are as follows:
1. Go to the Themes tab. The "Change color of" titles haven't been translated. The "Restore Defaults" button hasn't been translated either.
2. In Settings, there a lot of such examples. "Your Account" in the Account tab, "Change your Account Password" in the Password tab, "Connect to SUSI Hardware" in the Connect to SUSI Hardware tab, "Select Server" in the Server Settings tab, the "Save changes" button and so on.

**Screenshots of the issue**

screen shot 2017-12-05 at 2 39 18 pm
screen shot 2017-12-05 at 2 41 26 pm
screen shot 2017-12-05 at 2 41 32 pm
screen shot 2017-12-05 at 2 41 45 pm

**Would you like to work on the issue?**

Yes, I would like to work on this issue :)

### PR DESCRIPTION
**Pull request by Remorax**
Fixes issue #939.

Changes:
1. All the translation bugs have been fixed in settings and in the themes window.
2. In the themes window, "Restore to Defaults" has been changed to "Reset" as the translation for the former is very long in some languages, like Spanish, and so it was overflowing the container.
3. All the JSON files, English, Spanish, Dutch, Chinese, Hindi and Armenian have been updated appropriately as well.

Demo Link: http://hurt-scale.surge.sh
@mariobehling @isuruAb @rishiraj824  @madhavrathi Please review this ASAP :)

### CODE REVIEW

**Comment by isuruAb** [comment]
@madhavrathi  @rishiraj824  please review this

**Comment by isuruAb** [comment]
@mariobehling  @jigyasa-grover  @daminisatya  could you please merge this PR

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by Remorax** [comment]
Its' been 7 hours, and the Travis build still hasn't completed. Can this PR be merged, or else what is to be done?

**Comment by isuruAb** [comment]
@Remorax  please restart travis.

**Comment by Remorax** [comment]
@mariobehling Please merge this issue now

**Pull request merged**
