### PR TITLE
Update AccountTab.react.js

### PR DESCRIPTION
**Pull request by divyabaid16**
Fixes #[1859](https://github.com/fossasia/chat.susi.ai/issues/1859)

Changes: The styling elements are now stored in the variable and then used.

Demo link: https://pr-1684-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by AakashMallik** [comment]
Surge link?

**Comment by divyabaid16** [comment]
@AakashMallik  updated.

**Comment by AakashMallik** [comment]
@divyabaid16 Is this PR incomplete? Coz the PR mentioned mobileTab as well

**Comment by divyabaid16** [comment]
No, I will create a seperate PR for mobileTab.

**Comment by AakashMallik** [comment]
@divyabaid16 1 issue 1 PR. Also, if the changes are small, similar and mutually exclusive, pack them up in a single PR. It will take less time for us to review, and less time for mentors to merge.

**Comment by divyabaid16** [comment]
@AakashMallik  I think that there is no need to change Mobiletab.react.js because almost every component has different styling and changing it won't make a big difference. 
So I have updated the issue.

**Comment by AakashMallik** [comment]
Great.

**Comment by AakashMallik** [comment]
@divyabaid16 Travis failing btw. Fix it.

**Pull request merged**
