### PR TITLE
Fixed issue #2029 regarding address manipulations and Founder's name typo.

### PR DESCRIPTION
**Pull request by rajshah9914**
Fixes #[2029]

Changes: 
1.The address modified is as present on https://fossasia.org/ as shown on the extreme bottom of the 
  page.
  6 Eu Tong Sen Street #5-07 The Central, Singapore 059817

2.The actual display should be "Phuc Hong Dang" (name of founder of Fossasia which is spelled incorrectly)..

Screenshots for the change: 
Original :
contact
After Modifications:-
changed_contact

Edit:- Used prettier for better view in js..

### CODE REVIEW

**Comment by AakashMallik** [comment]
@rajshah9914 Update your branch.

**Comment by rajshah9914** [comment]
Sure @akshatnitd sir and @samagragupta

**Comment by rajshah9914** [comment]
@akshatnitd Sir , I have added the commit..Thanks for your review..

**Comment by rajshah9914** [comment]
@akshatnitd Sir, Please review this too..Had added commit message as per your request..

**Pull request merged**
