### PR TITLE
Fixes: #517 -Added a terms page

### PR DESCRIPTION
**Pull request by isuruAb**
Fixes issue #517 
Changes:  
- Added a term page. 
- referred the term page of LokLak . http://loklak.net/terms.
- used same terms list 

Demo Link: http://isuruab2.surge.sh/terms/

Screenshots for the change: 
screen shot 2017-07-21 at 1 49 29 pm
screen shot 2017-07-21 at 1 53 07 pm
screen shot 2017-07-21 at 2 02 33 pm

@mariobehling  @rishiraj824  @madhavrathi  @uday96  please review

### CODE REVIEW

**Comment by mariobehling** [comment]
Please check travis.

**Comment by madhavrathi** [comment]
@isuruAb the content looks fine to me. Please check Travis failures and also take in considerations comments of others.
Tuanks

**Comment by isuruAb** [comment]
@mariobehling @madhavrathi  fixed travis error .please check this again.

**Comment by rishiraj824** [comment]
Please see that the images are available and there is no horizontal scrolling in the left sidebar.
screenshot from 2017-07-21 14 43 07
Please change the colors of the Singup and login action buttons
screenshot from 2017-07-21 14 42 41

**Comment by madhavrathi** [comment]
@isuruAb Please check why the logo is not visible. please add the required commits. 
isuru

**Pull request merged**
