### PR TITLE
Fixes #63 & #64: Create a basic react app & deploy on gh-pages

### LINKED ISSUE #63: Deploy new react SUSI chat app on GitHub pages
- Deploy new chat app on Github pages.
- Update the README file

### PR DESCRIPTION
**Pull request by rishiraj824**
**Demo**
- [http://rishiraj.co/chat.susi.ai](http://rishiraj.co/chat.susi.ai)

### CODE REVIEW

**Comment by isuruAb** [comment]
travis is failing because travis.yml file is not there

**Comment by rishiraj824** [comment]
I don't know why it is failing since there is no .travis.yml file in the current repo. I think the Travis Integration is on which needs to be removed.

**Comment by rishiraj824** [comment]
I have integrated travis.yml for now to run the basic tests. @isuruAb @mariobehling

**Comment by isuruAb** [comment]
@rishiraj824  can you squash these commits into one ??

**Pull request merged**
