### PR TITLE
Changed component colors of dark theme

### LINKED ISSUE #1312: Component Colors of Dark theme should be changed
**Actual Behaviour**

The current component colors of dark theme are as previewed in the following image:
currentdarktheme
 

**Expected Behaviour**

All the component colors should be according to dark theme.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Akshat-Jain**
Fixes #1312 

**Changes:** Changed the component colors of dark theme to make them more suitable according to dark theme.

**Demo Link:** https://pr-1313-fossasia-susi-web-chat.surge.sh

**Screenshots for the change:** 

**Before:**
currentdarktheme
 
**Now:**
newdarktheme

### CODE REVIEW

**Comment by Akshat-Jain** [comment]
@PrP-11 @DNS-404 @anshumanv Please review. Thanks :-)

**Comment by Akshat-Jain** [comment]
@DNS-404 This is how the dark theme used to be.
@madhavrathi @isuruAb Please review. Thanks :-)

**Comment by Akshat-Jain** [comment]
@anshumanv The current dark theme component colors look odd (see the white color of message composer). I think we need to address that. Regarding the use of gradient for the main screen, this is how it used to be before.

**Comment by anshumanv** [comment]
You can just change the composer color and we should be good?

**Comment by Akshat-Jain** [comment]
@anshumanv This was the issue regarding this - https://github.com/fossasia/chat.susi.ai/issues/1142. It did not intend to modify the gradient color, but in the PR (https://github.com/fossasia/chat.susi.ai/pull/1170), some other guy did that. The code for the gradient color is still there, it is just overwritten by other color styling. That's why I changed it back to the gradient color.
However, I'll revert the change of the gradient color, if the mentors also think so. Thanks :-)

**Comment by Akshat-Jain** [comment]
@imjog Resolved the conflicts :-)
@mariobehling Please review. Thanks :-)

**Pull request merged**
