### PR TITLE
(Fixes #1670) Android and ios links working properly

### PR DESCRIPTION
**Pull request by garvitkhandelwal**
Fixes #1670 

The previous contributor was inactive so I took this issue.

Changes: changed paths from absolute to relative

Demo Link: https://pr-1875-fossasia-susi-web-chat.surge.sh

Screenshots for the change: 

screenshot 48
Clicking on google play link opens this

### CODE REVIEW

**Comment by garvitkhandelwal** [comment]
@AakashMallik  Please have a look at this.

**Comment by AakashMallik** [comment]
Did you make changes to git ignore? Coz I see two VS Code config files. Get them out of this PR.

**Comment by AakashMallik** [comment]
Was **Link** tag not working?

**Comment by AakashMallik** [comment]
@garvitkhandelwal We work on VS code to. And please unstaged those files and force push again. And yes the **a** tag seems to be okay.

**Comment by garvitkhandelwal** [comment]
@AakashMallik  Done. Let me know if it's okay now

**Comment by AakashMallik** [comment]
Nice. just update your branch and we are good to go.

**Comment by garvitkhandelwal** [comment]
screenshot 49
It shows merging is blocked

**Comment by garvitkhandelwal** [comment]
@akshatnitd  Please review this.

**Pull request merged**
