### PR TITLE
Fixes #107 - Map marker not rendering in map tile

### LINKED ISSUE #107: Map marker is not being rendered in the map tile
Map marker icon css is missing in the ChatApp.css
nomarker

### PR DESCRIPTION
**Pull request by uday96**
Added css for marker icon

withmarker

**Demo Link** : http://marker.surge.sh/

### CODE REVIEW

**Comment by uday96** [comment]
test

All tests passed locally. And I only added CSS, why is travis failing?

**Comment by chashmeetsingh** [comment]
Check the logs here: https://travis-ci.org/fossasia/chat.susi.ai/builds/237374167?utm_source=github_status&utm_medium=notification

Also I guess marker is not required as it's not there in the android and iOS clients. @Orbiter please confirm?

**Comment by uday96** [comment]
@chashmeetsingh the same test passes locally. I put the screenshot. Also, the marker is present in http://susi.ai/chat

**Comment by chashmeetsingh** [comment]
I restarted the build and all tests pass now🎉

**Pull request merged**
