### PR TITLE
Fixes #268: susi message search now works

### LINKED ISSUE #268: SUSI Search in message section not working
**Actual Behaviour**

message search in susi web is not working due to recent merges.

**Would you like to work on the issue?**

Yes, i will find the typo made in recent commits , fix it and send PR 
thanks.

### PR DESCRIPTION
**Pull request by madhavrathi**
Fixes issue #268 

Changes : Fixed Typo in actions/index.js

Demo Link: http://searchfix.surge.sh/

@rishiraj824 @uday1201 @daminisatya @isuruAb 
Please Review !

### CODE REVIEW

**Comment by rishiraj824** [comment]
@madhavrathi yes please change the color

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by madhavrathi** [comment]
closing this pull request as of now, due to some errors while squashing commits
Will reopen another one right now.
Thanks

**Comment by madhavrathi** [comment]
looks like this PR https://github.com/fossasia/chat.susi.ai/pull/273/files
made the changes which fixed the typo, so that was the reason for conflicts and my solution was implemented in this PR only so this issue is solved as of now
Thanks !

**Pull request closed without merging**
