### PR TITLE
Fixes #1374: Do not hide dropdown when searching

### LINKED ISSUE #1374: Top right menu disappears when using Search
In the top bar the menu disappears when search is activated.

screenshot from 2018-06-22 10-58-07

### PR DESCRIPTION
**Pull request by anshumanv**
Fixes #1374 

Changes: Do not hide dropdown when searching

Demo Link: https://pr-1375-fossasia-susi-web-chat.surge.sh

Screenshots for the change: 
image

### CODE REVIEW

**Comment by isuruAb** [comment]
please check responsive views of the app
screen shot 2018-06-22 at 9 41 29 pm

**Comment by anshumanv** [comment]
@isuruAb responsiveness issue already persists in the app and thus reported https://github.com/fossasia/chat.susi.ai/issues/1376 that can be taken up separately therefore.

**Comment by anshumanv** [comment]
@mariobehling I'm not sure if this is a browser issue but in my case everything seems to be aligned on all pages, tested on both chrome and firefox, can you please share your browser version and if possible a screenshot to help me understand better about what's missing so I can quickly work on a fix, please?

**Comment by mariobehling** [comment]
Ok, let's test step by step. Thanks.

**Pull request merged**
