### PR TITLE
shifting accounts api from susi to asksusi.com

### PR DESCRIPTION
**Pull request by nikhilrayaprolu**
Inreference to issue #30 , I amn't able to test this since the backend server requires client to be on https to make calls.
screenshot from 2017-01-01 18-38-45

### CODE REVIEW

**Comment by mariobehling** [comment]
@nikhilrayaprolu The goal of the issue is not to move the API to asksusi.com. The goal is to access the API on api.asksusi.com from asksusi.com.

**Comment by mariobehling** [comment]
@nikhilrayaprolu Please share the link to your setup. You can set your github page to https.

**Comment by nikhilrayaprolu** [comment]
https://nikhilrayaprolu.github.io/asksusi.com/#!/
but as the server api.asksusi.com is on http and the client on https ,request to the server are getting blocked due to mixed content loading

**Comment by mariobehling** [comment]
I successfully enabled https last night. Please try to adapt the code accordingly to make it work. Thank you.

**Comment by nikhilrayaprolu** [comment]
well @mariobehling thanks for enabling https.
but the CORS problem hasn't gone
screenshot from 2017-01-02 23-34-58
you can  check with the error on this page https://nikhilrayaprolu.github.io/asksusi.com/html/apps/forgotpassword/

**Pull request closed without merging**
