### PR TITLE
Fixes #176 - Option to show or hide password

### LINKED ISSUE #176: Option to show or hide password in Login SignUp Forms
**Actual Behaviour**

Currently the password input in forms masks the text. No option to show/hide the password in the text field

**Expected Behaviour**

Have an option to show/hide the password text.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by uday96**
Fixes issue #176 

**Changes:**
Added a Password Field with an option to show or hide password in the login and signup forms

**Demo Link:** http://showpassword.surge.sh/

**Screenshots for the change:**

login

signup

### CODE REVIEW

**Comment by uday96** [comment]
@rishiraj824 @isuruAb @madhavrathi please review :smile:

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by uday96** [comment]
@mariobehling Fixed merge conflicts. Unable to squash commits to merge master .

**Comment by uday96** [comment]
messed up while trying to squash commits. 
Kindly refer https://github.com/fossasia/chat.susi.ai/pull/222

**Pull request closed without merging**
