### PR TITLE
Added a final instruction :D

### PR DESCRIPTION
**Pull request by Beta-King**
This PR gives a last instruction to deploy the link to the web-browser to see the results of the website with surge :D

### CODE REVIEW

**Comment by Beta-King** [comment]
#1033 --> solves this issue :D

**Comment by Beta-King** [comment]
screen shot 2018-01-12 at 10 47 28 pm

**Comment by Beta-King** [comment]
@sayak119 thank you :D

**Comment by Beta-King** [comment]
No, i have to make a new one, mentors told me to do so @0x48piraj

**Comment by 0x48piraj** [comment]
Any references ?

**Comment by Beta-King** [comment]
Its in my Task instances :D

**Comment by samyakbvs** [comment]
@Beta-King Try to do something more in this PR

**Comment by madhavrathi** [comment]
@Beta-King Thanks for your PR. As mentioned by your fellow developers, this PR might not stand up to standards of PR's we usually expect. If possible, try to fix one more issue with this PR, and we'll be more than happy to merge your PR. Let me know what you think and keep up the good work. Thanks

**Comment by Beta-King** [comment]
Yeah, ill work on it ASAP :D

**Comment by Beta-King** [comment]
No actually i was meant to close this PR i talked to the mentors and they said that there is not much more to do with documentation section but yeah ill work on improving other aspect of this repo :D

**Pull request closed without merging**
