### PR TITLE
Improve indentation of some files

### LINKED ISSUE #1046: Indentation not correct
Indentation of some css files are not correct.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by DNS-404**
Fixes #1046 

Changes: Just improving indentation of some files.

### CODE REVIEW

**Comment by DNS-404** [comment]
Won't a pull request do the job? Codacy check is passed. It says this on this pull request.

**Comment by anshumanv** [comment]
Agreed with @sudheesh001. If the issue is about lint please be generic about your fix. :smile:

**Comment by DNS-404** [comment]
@sudheesh001 No this issue wasn’t existing or being shown on codacy previously. 😅
I don’t really know what is lint, code coverage and coala. I’ll study them.
For now, should I close the issue and delete this PR?

**Comment by sudheesh001** [comment]
I'd just close this for now. Please look into test coverage and improving coverage for this repository.

**Pull request closed without merging**
