### PR TITLE
Remove x-scroll from Intro video dialog

### LINKED ISSUE #1057: Horizontal scrollbar in Youtube Intro Modal
**Actual Behaviour**
Horizontal scrollbar in Youtube Intro Modal

**Expected Behaviour**
The modal should not have any scroll

**Screenshots of the issue**
capture

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by jajodiaraghav**
Fixes #1057 

Screenshots for the change: 
capture

### CODE REVIEW

**Comment by saurabh30** [comment]
@jajodiaraghav  please provide the deployment link...I think these changes will make the dialog unresponsive.

**Comment by saurabh30** [comment]
@jajodiaraghav These changes will make video dialog unresponsive.

**Comment by jajodiaraghav** [comment]
Hi @saurabh30 
I am sorry for not taking case of the responsiveness earlier. I have updated the issue.
Please have a look :)

**Comment by jajodiaraghav** [comment]
There you go: http://used-guitar.surge.sh/

@tstreamDOTh Please merge

**Pull request merged**
