### PR TITLE
Fixes #219 - style swipable websearch rss tiles

### LINKED ISSUE #219: Fix the swipe styling for websearch and rss tiles
**Actual Behaviour**

The styling for websearch and rss tiles is not proper regarding the swipe aspect. The users wouldnt know that they are swipable the way the tiles are rendered now.

**Expected Behaviour**

Style the tilles so that the users would know that they are swipable

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by uday96**
Fixes issue #219 

**Changes:** 
The swipale websearch rss tiles now have dots indicating the number of tiles and with the current tile dot highlighted and arrows to navigate the tiles.

**Demo Link:**  http://styleswipe.surge.sh/

**Screencast:** 

styleswipe

### CODE REVIEW

**Comment by uday96** [comment]
@rishiraj824 @isuruAb @madhavrathi please review :smile:

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by uday96** [comment]
@isuruAb once the count feature is implemented for websearch from the server side too that won't be an issue. It's already implemented for RSS and table.

**Comment by uday96** [comment]
@mariobehling resolved conflicts. unable to squash due to merge commits.

**Pull request merged**
