### PR TITLE
Fixes #580 added proper logos

### LINKED ISSUE #580: Logo not showing up in overview page
**Actual Behaviour**

There was a merge in between commits, so there is an issue with logos in secure area. Logos are not in proper manner for smaller screens

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by madhavrathi**
Fixes issue #580

Changes: Fixed logos in secure area for smaller screens

Demo Link: http://susi-madhav.surge.sh/overview

Screenshots for the change: 

mario

### CODE REVIEW

**Comment by madhavrathi** [comment]
@rishiraj824 @uday96 @isuruAb Please review. Thanks

**Comment by madhavrathi** [comment]
@rishiraj824 @uday96 @isuruAb @mariobehling I have made the changes please review  http://susi-madhav.surge.sh/overview
Thanks

**Comment by mariobehling** [comment]
The below area is still further left than upper sections:
screenshot from 2017-07-23 19-28-35

**Comment by madhavrathi** [comment]
align
@mariobehling I aligned it properly, Please review. I will try to speed up my UI fix work, apologies for delay

**Comment by mariobehling** [comment]
@madhavrathi You also increase the logo of OSI. The OSI logo should have a bigger height, cause it is overall small than the Github logo.

**Comment by madhavrathi** [comment]
@mariobehling Increased the size of osi logo. Please review http://susi-madhav.surge.sh/overview
Thanks

**Comment by mariobehling** [comment]
* Please increase OSI logo to 85x85 px and align both logos in one line in the middle
* Slightly increase the distance between the logos

**Comment by madhavrathi** [comment]
@mariobehling Changes done. Please review http://susi-madhav.surge.sh/overview

**Comment by mariobehling** [comment]
Thank you.

**Pull request merged**
