### PR TITLE
Added Tab layout for settings

### PR DESCRIPTION
**Pull request by madhavrathi**
Fixes issue #761 

Changes: Added Tab layout for settings

Next Steps: 
- [x] Fix the error on state change
- [x] Fix the app bar for smaller screens
- [x] Add responsiveness 

Screenshot : 
settings

Demo Link: http://settings-susi.surge.sh/settings

### CODE REVIEW

**Comment by madhavrathi** [comment]
@rishiraj824 @uday96 @isuruAb Please Review
Thanks

**Comment by mariobehling** [comment]
* Please don't use black colors. Use the existing colors, white, gray and blue.
* Please don't position it on the very left of the screen and neither on the very top. Leave space and align it in the same position as the overview page

screenshot from 2017-08-28 23-22-26

Maybe something along the lines the following:

screenshot from 2017-08-28 23-25-26

**Comment by madhavrathi** [comment]
@mariobehling I have fixed the design. Please Review: http://settings-susi.surge.sh/settings
screen
Thanks

**Comment by rishiraj824** [comment]
@madhavrathi Aligning the text to the left and reducing the shadow would make it look good I guess. Also, we can add a `#f2f2f2` background to the active setting tab.

**Comment by mariobehling** [comment]
Ok, thanks. Let's iterate from here in follow up issues/PRs. Good job!

**Pull request merged**
