### PR TITLE
mention chrome extension on overview page

### LINKED ISSUE #1263: Include Link to SUSI chromebot in the overview page
**Actual Behaviour**
There's no mention about the SUSI chromebot on the overview page

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by prateekiiest**
Fixes #1263 

It now mentions about Chrome extension and Firefox extensions

Demo Link : http://lopsided-dogs.surge.sh/

**Screen-shots of the image**

screenshot 102

### CODE REVIEW

**Comment by prateekiiest** [comment]
Deployed URL : http://lopsided-dogs.surge.sh

Sorry for the late upload. I was having some deployment issues lately. Finally fixed them

**Comment by prateekiiest** [comment]
@hkedia321 updated firefox bot as well.

**Comment by hkedia321** [comment]
@prateekiiest It looks like you have made changes only in the surge (http://lopsided-dogs.surge.sh/) and not in this PR. Please update this PR as well. 
Do remember to add `and` between Chrome Extension and Firefox Extension, and add a space after full stop.
image
Also, it is a good practice to have a single commit for a PR. Cheers!

**Comment by prateekiiest** [comment]
ok, I will update with the changes

**Comment by prateekiiest** [comment]
@akshatnitd @stealthanthrax 

When I do 
`$ git reset --soft HEAD~4`

I get a whole bunch of commits for all other repositories under my GitHub Folder.
It might possibly due to the wrong head position or previously unstaged commits

I am showing the log here
screenshot 103

So I am not taking any chance by pushing this to this branch as it will totally mess up the commit history.

I will be glad if someone can help me on this.

While I can figure the reason behind these, would be ok if this can be squashed and merge with the `Squash, Merge` option ?

**Comment by mariobehling** [comment]
We need to add this info elsewhere. Let's follow up on this later. It is low priority atm. Thanks.

**Pull request closed without merging**
