### PR TITLE
notFound: hide login and signup buttons when logged in

### LINKED ISSUE #1997: NotFound: Hide signup and login buttons when logged in
**Actual Behaviour**

Currently when the user is logged in, signup and login buttons are visible to the user on Not Found page

**Expected Behaviour**

It should be hidden.

**Screenshots of the issue**

image

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by AdityaSrivast**
Fixes #1997 

Changes: When user is logged in, login and signup buttons should not be visible on 404 page

Demo Link: https://pr-2000-fossasia-susi-web-chat.surge.sh

Screenshots for the change: 

image

### CODE REVIEW

**Comment by AdityaSrivast** [comment]
@hkedia321  @DNS-404 Can you please review?

**Comment by AdityaSrivast** [comment]
@akshatnitd @Orbiter  Can you please review?

**Comment by hkedia321** [comment]
@AdityaSrivast Looks good, but please check why codacy is failing.

**Comment by AdityaSrivast** [comment]
@hkedia321 There's a mismatch between eslint configuration in the repository and that on codacy, regarding the use of single and double quotes.

Each time I commit, it changes double-quotes to single-quote in precommit script. But, codacy is expecting double quotes. Hence, causing the error.

**Comment by AdityaSrivast** [comment]
@akshatnitd made the changes

**Pull request merged**
