### PR TITLE
position of top right menu button corrected

### LINKED ISSUE #2041: Inaccurate positioning of topRightMenu
**Actual Behaviour**

issue1
It is difficult for the user to find it.

**Expected Behaviour**

corrected1

This is how it is in the homepage:

corrected2

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by ArexJambusarwala**
Fixes #2041 

Changes: Removed a right-margin of -8px from TopRightMenu.

Screenshots for the change: 
corrected1

### CODE REVIEW

**Comment by ArexJambusarwala** [comment]
Demo Link: http://pr-2041-fossasia-susi-web-chat.surge.sh/support

**Comment by ArexJambusarwala** [comment]
Demo link: http://pr-1930-fossasia-susi-skill.surge.sh/

**Comment by ArexJambusarwala** [comment]
It should work now.

**Comment by samagragupta** [comment]
> Demo Link: http://pr-2041-fossasia-susi-web-chat.surge.sh

It should be 2042

**Comment by ArexJambusarwala** [comment]
> > Demo Link: http://pr-2041-fossasia-susi-web-chat.surge.sh
> 
> It should be 2042

On running surge and using 2042, it says I donot have permission to publish.

**Comment by AakashMallik** [comment]
@ArexJambusarwala We are going to reuse the topbar so this issue fix is redundant. There is a PR in WIP state that is trying to fix this. Sorry I was a bit late in letting you know about this.

**Pull request closed without merging**
