### PR TITLE
Thumbs up and down cannot be changed

### LINKED ISSUE #1443: Thumbs up or down cannot be changed
The feedback once given on an interaction should not be changeable, otherwise it will cause inconsistencies in the feedback logs that will be used for analysis.

**Would you like to work on the issue?**

No, anyone can assign the issue to himself/herself.

### PR DESCRIPTION
**Pull request by thakursaurabh1998**
Fixes #1443 

Changes: If feedback was already given, I added a return statement with a console log `Already rated` in the function `rateSkill` where ajax request was being sent to up vote or down vote.

Demo Link: https://pr-1453-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by thakursaurabh1998** [comment]
So any other solution, how this can be solved? @fragm3

**Comment by fragm3** [comment]
@thakursaurabh1998 right now, the skill rating is not working as you can see in console if you try to rate. It would be nice if you could see the server side implementation and get it working.

**Comment by thakursaurabh1998** [comment]
@akshatnitd That's what it's doing. The logging is just for debugging.

**Comment by akshatnitd** [comment]
Reflect changes on the UI as well, rather than just coming out of the function.

**Comment by AnupKumarPanwar** [comment]
@fragm3 @thakursaurabh1998 For a server-side implementation it would require the user to log in to rate the skill so that all the feedbacks can be uniquely identified. But it was decided in a meeting that anonymous feedbacks are also important and the implementation has to be done on the client side only.

**Comment by akshatnitd** [comment]
@thakursaurabh1998 Can you please update regarding the progress?

**Comment by akshatnitd** [comment]
@thakursaurabh1998 If you aren't working on it, can I take this up ?

**Comment by thakursaurabh1998** [comment]
@akshatnitd only thing left is a ui notification, I asked if there is any pre-built snackbar or toast for notifications or can I add one myself?

**Comment by mariobehling** [comment]
@thakursaurabh1998 Good catch!

@akshatnitd If you have any improvements you can also commit to @thakursaurabh1998 branch and update it. Would be great to see this kind of team work. Cheers.

**Comment by thakursaurabh1998** [comment]
This issue is free to take for anybody.

**Comment by mariobehling** [comment]
Closing this due to inactivity.

**Comment by AnupKumarPanwar** [comment]
@mariobehling @anshumanv @akshatnitd I think we can go ahead with this. The code works as desired, just the user doesn't get a notification that feedback once given cannot be changed. I think we don't need that as, not being able to change the feedback itself indicates that.

**Comment by thakursaurabh1998** [comment]
I will be happy if it is merged :smile:

**Pull request closed without merging**
