### PR TITLE
forgot password fixed

### LINKED ISSUE #1558: Forgot password link is not working
**Actual Behaviour**

Forgot password link in password tab of settings page is not working .

**Expected Behaviour**

Forgot password should open a model or page .

**Steps to reproduce it**

Go to the settings page. Click on the forgot password link in the password tab. It gives 404.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #1558 

Changes: Fixed the forgot password link in Passwords tab of Settings page

Demo Link: https://pr-1615-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by Akshat-Jain** [comment]
Please check the inconsistencies in the 2 screenshots below:

This one is screenshot from your deployment link:
screenshot 2018-10-12 at 12 48 31 am

This screenshot is when we click on `Forgot Password` from the Login dialog box:
screenshot 2018-10-12 at 12 48 51 am

**Comment by samagragupta** [comment]
@Akshat-Jain @akshatnitd  @fragm3 Please review the changes.

**Comment by samagragupta** [comment]
@akshatnitd The two components `ChangePassword` and `ForgotPassword` were already made. I have just made some changes in them.

**Comment by samagragupta** [comment]
@Akshat-Jain @anshumanv @mariobehling Please review.

**Comment by isuruAb** [comment]
@Akshat-Jain  can you review this again.

**Comment by samagragupta** [comment]
@Akshat-Jain Resolved the conflicts.
Please merge the PR.

**Pull request merged**
