### PR TITLE
Migrate Blog to @material-ui/core

### LINKED ISSUE #2069: Upgrade material-ui to @material-ui/core
**Actual Behaviour**

The current version of Material UI module being used for this project is now deprecated, and should be changed to @material-ui/core module.

**Expected Behaviour**

Use new module with support

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2069 

Changes: -
1. Migrated Blog.react.js to a newer material UI version
2. Used style components and reused it for UI.

Demo Link: https://pr-2094-1-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by fragm3** [comment]
@akshatnitd @harsh-jindal please review.

**Comment by harsh-jindal** [comment]
@fragm3 Can you improve this card footer it would be better if the date and name came on one line without breaking.
Screenshot 2019-05-17 at 12 06 13 PM

**Comment by fragm3** [comment]
@akshatnitd @harsh-jindal Made the changes, please review

**Comment by harsh-jindal** [comment]
@fragm3 In mobile view "Published on {Date}" moves out of place and for footer in mobile view either make the div scrollable or make it a 2 column layout.

**Comment by fragm3** [comment]
@harsh-jindal @akshatnitd made the changes

**Pull request merged**
