### PR TITLE
[WIP]initial steps for docs page

### PR DESCRIPTION
**Pull request by madhavrathi**
Fixes issue #515

Changes: Added initial docs page.
Things left : 
1)adding feature image to top.
2) Adding feature image to Running on localhost and Connecting to hardware section
I will add them in this PR only, just review for any suggestions
Demo Link: http://susi-docs.surge.sh/

Screenshots for the change: 
screen1
screen2
screen3

@rishiraj824 @uday96 @isuruAb Please suggest any changes.

### CODE REVIEW

**Comment by madhavrathi** [comment]
@isuruAb Please check again, i have fixed the link http://susi-docs.surge.sh/docs
Thanks for the blog, it helped a lot

**Comment by madhavrathi** [comment]
http://susi-docs.surge.sh/docs
@rishiraj824 @uday96 @isuruAb Please review the following changes : 
1) added responsive pie-chart for languages.
2)added featured image for top.
I have also checked the page for various screen sizes.
@mariobehling Please review the content.
Thanks

**Comment by rishiraj824** [comment]
@madhavrathi According to me the featured image is taking too much space on the top. We can either reduce it or keep it simple as `Developer Guide`. We can add about Flux in the Framework used section.

**Comment by uday96** [comment]
@madhavrathi Yes, Please resize featured image

**Comment by madhavrathi** [comment]
@rishiraj824 @isuruAb I have resized the featured images and added flux as an architecture used. Please review. Regarding the size of other images, I believe we need the current size as we need to display a particular image on the whole page, resizing them will make the page look blank. Please provide your views in this
Thanks

**Comment by mariobehling** [comment]
* text full of errors
* Language Breakdown not correct for complete SUSI AI project. Server and Android apps not included. This is not only a page for the chat app.

**Comment by mariobehling** [comment]
* Frameworks Used not correct. Susi is more than just the chat app.

**Comment by mariobehling** [comment]
Please follow https://developers.google.com/actions/ more closely. Just create the page and add videos etc. from the students for now.

**Comment by mariobehling** [comment]
@madhavrathi I am merging this as work in progress. Please follow up in the issue itself about next steps.

**Comment by madhavrathi** [comment]
@mariobehling Okay, I will follow up the issue for next steps.
Thanks

**Pull request merged**
