### PR TITLE
Fixes #632 - Added link to openstreet maps in map actions

### LINKED ISSUE #632: Include the link from anchor in map action type as the link in answer has been removed
**Actual Behaviour**

The link to open street maps has been removed from answer action type.

**Expected Behaviour**

Use the anchor action type link to display in the chat bubble

Refer : https://github.com/fossasia/susi_server/pull/418

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by uday96**
Fixes issue #632 

**Changes:**
 - Added map anchor

**Demo Link:** http://udaytheja1.surge.sh/

**Screenshots for the change:** 

mapanc

### CODE REVIEW

**Comment by uday96** [comment]
@rishiraj824 @isuruAb @madhavrathi Please review.

**Comment by mariobehling** [comment]
There is related issue on the server here https://github.com/fossasia/susi_server/issues/429

Please resolve it in this setting.

> The map features have some confusing way of display and text. Please fix the following:
> * [ ] Expected: Singapore is a place in Asia with a population of ... Here is a map.
>   * "Here is a map" should incorporate the link already. No need to show the link additionally.
>   * Do not show the info on OpenStreetMap and info "OpenStreetMap is a..."
> * [ ] Do not show "Link to an OpenStreetMap for your location." It is not needed. We already have the link above.

**Comment by mariobehling** [comment]
@uday96 In this PR https://github.com/fossasia/chat.susi.ai/pull/561 the width of the map was already adapted. Now, I see the full width is not used anymore. Why not?

**Comment by uday96** [comment]
@mariobehling Now the response from the server doesn't have the link to openstreet maps so the text content has been reduced. The chat bubbles are auto sized according to text. Now since the link is not present and there is only little text, the chat bubbles are not occupying the entire width. Will make a PR to Fix the width

**Comment by mariobehling** [comment]
@isuruAb Thanks for engaging. Did you look at my comments before you approved? What is your input?

**Comment by mariobehling** [comment]
> Now the response from the server doesn't have the link to openstreet maps so the text content has been reduced. 

We still want the link, but it should be part of the text.

**Comment by uday96** [comment]
@mariobehling Yes. I understand. I'm looking at the server code to try to change the response sent from server for map. Will first implement changes in the server side and then incorporate those in the client side.

**Comment by uday96** [comment]
@mariobehling Now the changes have been updated.

mapan

Please check http://udaytheja1.surge.sh/

**Comment by mariobehling** [comment]
"Link to OpenStreetmap.." -> "Here is a map."

**Comment by uday96** [comment]
The changes will be automatically handled on client side after https://github.com/fossasia/susi_server/pull/459 gets merged

**Pull request merged**
