### PR TITLE
settings:modify delete account UI

### LINKED ISSUE #1996: settings: make delete account UI consisitent with accounts.susi.ai
**Actual Behaviour**

Currently, there's a pending PR in accounts.susi.ai, which will modify the UI

**Expected Behaviour**

Both the UI's should be same

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by AdityaSrivast**
Fixes #1996 

Changes: make delete account UI consistent with accounts.susi.ai

Demo Link: https://pr-2050-fossasia-susi-web-chat.surge.sh

Screenshots for the change: 

image

### CODE REVIEW

**Comment by AdityaSrivast** [comment]
@hkedia321 @akshatnitd Can you please review?

**Comment by AdityaSrivast** [comment]
Sure @AakashMallik thanks for correcting

**Comment by AdityaSrivast** [comment]
@AakashMallik made the changes :)

**Comment by AakashMallik** [comment]
> screenshot-pr-2050-fossasia-susi-web-chat surge sh-2019 02 22-23-31-48

Fix this...

**Comment by AdityaSrivast** [comment]
@AakashMallik This PR is focussed on modifying UI for delete account. But we surely can raise another issue for making both the menu with even heights for all options in settings menu.
Thanks

**Comment by AakashMallik** [comment]
> @AakashMallik The PR is focussed on modifying UI for delete account. But we surely can raise another issue for making both the menu with even heights for all the options in settings menu.
> Thanks

Sure, if that is how you wish to proceed. No problem. @AdityaSrivast

**Comment by AdityaSrivast** [comment]
@akshatnitd @Akshat-Jain @hkedia321 Can you please review?

**Comment by AdityaSrivast** [comment]
@akshatnitd made the changes

**Comment by AdityaSrivast** [comment]
@fragm3 made the changes

**Pull request merged**
