### PR TITLE
Fixes #1013. Prevent Left navigation drawer content from scrolling horizontally.

### LINKED ISSUE #1013: Navigation drawer content scrolls horizontally when closing from a mobile device.
**Actual Behaviour**

image

**Expected Behaviour**
bug_resolved

While closing the navigation drawer, the menu items should not scroll horizontally.

**Steps to reproduce it**
Step 1: From any mobile device open http://chat.susi.ai/overview
Step 2: Try to open and close the navigation drawer by swiping a finger from the left edge of the screen.

**Would you like to work on the issue?**
Yes, i have resolved this issue. Should i create a pull request?

### PR DESCRIPTION
**Pull request by kapillamba4**
Fixes issue #1013.

Prevent Left navigation drawer content from scrolling horizontally by modifying drawer container's overflow css property.

Changes: Just changed the style for container of left navigation drawer from default "auto" to "hidden". 
Demo Link: https://pr-1016-fossasia-susi-web-chat.surge.sh/overview

Screenshots for the change:
image

### CODE REVIEW

**Comment by kapillamba4** [comment]
@sayak119, done i have mentioned the issue number.

**Comment by kapillamba4** [comment]
@sayak119 I cannot change the url from 
https://pr-1016-fossasia-susi-web-chat.surge.sh
to
https://pr-1016-fossasia-susi-web-chat.surge.sh/overview
as directly visiting the latter url will give you a page not found error as surge does not allow this.
image
You need to manually go to overview section. Same applies for PR #1011.

**Comment by kapillamba4** [comment]
@madhavrathi can you please review this.

**Comment by madhavrathi** [comment]
@kapillamba4 For accessing all routes on your deployment link, you need to make a copy of index.html file in build folder while choosing the name of your deployment, and rename it to 200.html. Read this blog(https://blog.fossasia.org/react-routes-to-deploy-404-page-on-gh-pages-and-surge/) for more info and please update the deployment link.

**Comment by kapillamba4** [comment]
@madhavrathi updated the deployment link 👍

**Pull request merged**
