### PR TITLE
Fixes #211 :change button colour according to the theme

### LINKED ISSUE #211: Change Button Colours according to the theme
**Actual Behaviour**

Now Colours of buttons are not changing when user change the theme.

**Expected Behaviour**

It should change colour according to the theme user choose.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by isuruAb**
Fixes issue #211 

Change background and font colour of buttons when user switch between themes.
 
Demo Link: http://susi-patch-211.surge.sh/

### CODE REVIEW

**Comment by uday96** [comment]
@isuruAb can you change the button colour in the forgot password change also?
Looks good :+1:

**Comment by isuruAb** [comment]
@uday96  added

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by rishiraj824** [comment]
@isuruAb Please squash your commits as one.

**Comment by mariobehling** [comment]
@isuruAb Please resolve merge conflicts.

**Pull request closed without merging**
