### PR TITLE
Update Android Screenshot (#1789)

### LINKED ISSUE #1798: Android Screenshots are old.
**Actual Behaviour**
Android Screenshots are old.

**Expected Behaviour**
Should be updated with new screenshot.

**Steps to reproduce it**

https://chat.susi.ai/overviewe
**LogCat for the issue**

**Screenshots of the issue**
screenshot from 2018-12-08 15-15-07

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by niteshkumarniranjan**
Fixes #1798 

Changes: 
Updates Android App Screenshot.

Demo Link: https://pr-1799-fossasia-susi-web-chat.surge.sh

Screenshots for the change: 
screenshot from 2018-12-08 18-16-51

### CODE REVIEW

**Comment by jogendra** [comment]
@Akshat-Jain @akshatnitd @anshumanv Please review

**Comment by AakashMallik** [comment]
@niteshkumarniranjan Exactly what @akshatnitd sir said. Also, speed up the gif.

**Comment by niteshkumarniranjan** [comment]
@aksharnitd No idea why the web results is not coming up.

**Comment by niteshkumarniranjan** [comment]
@rajvaibhavdubey Its not working 
screenshot_2018-12-09-00-33-32-083_ai susi

**Comment by mariobehling** [comment]
Closing this. SUSI.AI is work in progress and maybe some things don't always work, but we need to show screenshots that work.

**Pull request closed without merging**
