### PR TITLE
Fixes #470 - Enhances Feedback ui

### LINKED ISSUE #470: Enhance UI for Feedback System
**Expected Behaviour**
Follow Facebook reactions implementation to add a hover state.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by rishiraj824**
Fixes issue #470 

Changes: 
- Added hover state similar to Messenger Feedback

Demo Link: 
http://susi-feedback.surge.sh

### CODE REVIEW

**Comment by uday96** [comment]
e

The feedback icons are not aligned with their messages for me. Can you check once?

**Comment by rishiraj824** [comment]
screenshot from 2017-07-20 13 41 09
@uday96 Please check again its okay for me here.

**Comment by mariobehling** [comment]
Why is the message box not using the fully available width?

@rishiraj824 Please help to focus more on priority tasks, e.g. getting the voice input right.

**Comment by rishiraj824** [comment]
@mariobehling  I am working on the fix for the Voice Input on Phones already. I will definitely update you with the fix and send a PR. Meanwhile the issue in this picture is because of Grammarly extension and the one in there https://github.com/fossasia/chat.susi.ai/issues/534 This PR should fix this I suppose - https://github.com/fossasia/chat.susi.ai/pull/544

**Comment by rishiraj824** [comment]
@mariobehling My primary focus is the issue of voice input not working on phones only. I will update you soon as an when I find the fix. Meanwhile, the textarea appearing small is because of the Grammarly extension and a similar issue has been created https://github.com/fossasia/chat.susi.ai/issues/534. This is fixed in the PR https://github.com/fossasia/chat.susi.ai/pull/544

**Comment by mariobehling** [comment]
Actually I misunderstood this change. There is no need for this change. Previous one was clearer. Advantage of hover effect here is unclear for mobile UI.

**Pull request merged**
