### PR TITLE
Added a link to video, to improve surge deployment docs

### PR DESCRIPTION
**Pull request by samyakbvs**
A screencast made by me while deploying SUSI on surge

### CODE REVIEW

**Comment by isuruAb** [comment]
please squash your commits

**Comment by samyakbvs** [comment]
Thank you @SaptakS for merging the master branch but after he merged I am not able to squash as my commits are lost as they were done long before

**Comment by samyakbvs** [comment]
They are so below that the commits aren't appearing in the terminal

**Comment by samyakbvs** [comment]
Thank you so much!

**Pull request merged**
