### PR TITLE
#598 #553 #592 - Improvements of App Bar , make a separate component for app bar

### PR DESCRIPTION
**Pull request by isuruAb**
Fixes issue #598 #553 #592
 
Changes:
Improve the UI of app bar 
make separate component for the app bar 
add new app bar to every static page

Demo Link: http://isuruab.surge.sh/

Screenshots for the change: 
screen shot 2017-07-24 at 9 58 13 pm
screen shot 2017-07-24 at 9 58 33 pm

@mariobehling  @rishiraj824  @uday96  @madhavrathi  please review this.

### CODE REVIEW

**Comment by rishiraj824** [comment]
Please check once the underline is missing as mentioned in this issue.https://github.com/fossasia/chat.susi.ai/issues/592

> implement an underline just like Google sites

 Rest looks good.

**Comment by isuruAb** [comment]
@rishiraj824  underline is there. but it is white. could you please suggest a colour. @mariobehling  any suggestions?

**Comment by isuruAb** [comment]
@rishiraj824  please check it again. 
screen shot 2017-07-24 at 11 00 55 pm

**Comment by mariobehling** [comment]
* Please add app bar to team page as well
* Match app bar distances of: https://api.ai and slightly increase distance to logo but reduce distance between menu items
* Match font size of https://api.ai

**Comment by mariobehling** [comment]
* App bar not consistent on all pages
* Previous comments still not solved
* Missing underline

**Comment by isuruAb** [comment]
@mariobehling  please check the link again. http://isuruab.surge.sh/team

**Comment by mariobehling** [comment]
Plesae resolve conflicts.

**Comment by mariobehling** [comment]
Please implement dropdown menu in the same way as on chat page itself.
screenshot from 2017-07-25 20-02-15

**Comment by isuruAb** [comment]
@mariobehling  Please check it again i have done those changes.
http://isuruab.surge.sh/overview

**Comment by mariobehling** [comment]
Good job! Thank you.

**Pull request merged**
