### PR TITLE
Added Skill Section in overview page

### PR DESCRIPTION
**Pull request by madhavrathi**
Fixes issue #622 

Changes: Added skills section in the overview page.

Demo Link: http://susi-madhav.surge.sh/overview

Screenshots for the change: 
yo

### CODE REVIEW

**Comment by madhavrathi** [comment]
@rishiraj824 @uday96 @isuruAb Please Review.
Thanks

**Comment by madhavrathi** [comment]
@mariobehling I have done this in PR for issue https://github.com/fossasia/chat.susi.ai/issues/621 . Should i do that in this PR too ?

**Comment by mariobehling** [comment]
@madhavrathi Yes, please.

**Comment by madhavrathi** [comment]
@mariobehling Done. Please review http://susi-madhav.surge.sh/overview

**Pull request merged**
