### PR TITLE
Add Custom Theme to settings fixes #1461

### LINKED ISSUE #1461: Add theme preview to "theme tab" in settings and take "themes" from drop-down in chat
The theme has a live preview on the live site. This is a nice feature, but it is not central to the app. We can achieve the same feature by having a preview on the themes folder. Please integrate this feature into the settings area (https://chat.susi.ai/settings). Here is a rough wrap up.

screenshot from 2018-07-16 20-16-15

Please also take out "themes" from the burger menu drop-down.

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #1461

By mistake, I rebased wrong files which messed up the commit for PR: https://github.com/fossasia/chat.susi.ai/pull/1472

Changes: Added theme changer functionality in Settings,also keeping theme changer in nav bar.
Added preview theme

Note: Some UI fixes needs to be done and can be done in subsequent PRs.

Demo Link: https://pr-1461-fossasia-susi-web-chat.surge.sh (Updated)

ScreenShot: 
screen shot 2018-07-26 at 7 23 09 pm

### CODE REVIEW

**Comment by fragm3** [comment]
Working on it.

**Comment by fragm3** [comment]
@mariobehling redirect to chat home is fixed. Please review this. I can create sub issue for preview part.

**Comment by fragm3** [comment]
@mariobehling @akshatnitd Added preview option, please review. Surge link is same as in description.

**Comment by fragm3** [comment]
@anshumanv Done!

**Comment by fragm3** [comment]
@akshatnitd most of the errors are due to double quote, complexity issue. I fixed the arrow function errors. Please review

**Comment by Akshat-Jain** [comment]
@fragm3 There still are Codacy errors which are fixable. For example, use parentheses around arrow function argument. Please check Codacy errors again. Thanks :-)

**Comment by fragm3** [comment]
Updated the branch, fixed those Codacy errors, please review @Akshat-Jain

**Comment by mariobehling** [comment]
@fragm3 

> redirect to chat home is fixed. Please review this. I can create sub issue for preview part.
Surge link: https://pr-1461-2-fossasia-susi-web-chat.surge.sh

Usually subissues are a good idea. As this is one feature, it is difficult to separate here though. Please help to implement it within this issue. Thank you.

**Comment by fragm3** [comment]
@mariobehling I have already rebased the commits and added the preview section as required.

Screenshot: screen shot 2018-07-26 at 7 23 09 pm

Link: https://pr-1461-fossasia-susi-web-chat.surge.sh (Updated)

**Comment by fragm3** [comment]
@hkedia321 Hi, I had already added a note for UI fixes. Can we please do UI fixes in subsequent PR?

**Pull request merged**
