### PR TITLE
Removed red outline on logo onClick-Solves issue(#1588)

### LINKED ISSUE #1588: Red line in Upper left Logo clicking
**Actual Behaviour**
When you click the logo in the upper left corner it is encircled by a red dotted line, when deactivated it becomes a blue line in a blue that is different from the background color

**Expected Behaviour**

No need for link highlighting.

**Screenshots of the issue**

susichatt

**Would you like to work on the issue?**

no

### PR DESCRIPTION
**Pull request by pranav1698**
Fixes #1588 

Changes: 
The red outline that appeared on the logo on click does not appear now
Demo-Link:  http://1596-fossasia-susi-web-chat.surge.sh/

GIF for the change: 
chat-susi

### CODE REVIEW

**Comment by pranav1698** [comment]
@fragm3 please review now

**Comment by pranav1698** [comment]
chat-susi-1
Here is the old gif

**Comment by pranav1698** [comment]
@fragm3 @yashasvi128 If all the checks are ticked, please merge it because I want to work on other issues also

**Comment by rupav** [comment]
@pranav1698 it needs to be approved someone with write access too. 
Also you can always start working on other issues by creating a different branch on your local repo.

**Comment by pranav1698** [comment]
Thanks @rupav, for the suggestion

**Pull request merged**
