### PR TITLE
Fixes #192 (Partly) - Save Theme Settings according to user

### LINKED ISSUE #192: Save Theme Setting according to the user
**Actual Behaviour**

This is a sub-issue for #183. There is no theme setting preferred for the user. 

**Expected Behaviour**

One needs to throw the theme setting to the server.

**Would you like to work on the issue?**

Anyone can take the issue.

### PR DESCRIPTION
**Pull request by uday96**
Fixes issue #192 (Partly)

**Changes:**

  * Added a UserPreferences Store to save all user preferences or defaults.
    This can be further used to add other things and remove hard coded configurations - https://github.com/fossasia/chat.susi.ai/issues/183
 * Added a settings option and dialog, which consists of change default theme option as of now.
   The default theme is updated in the UserPreferenceStore on submit (check console.log)
 * When the page is initially loaded the theme is queried from the default theme in user preferences and set accordingly

Needs implementation of pushing the user preferences store data to server (whenever the user logs out and must be pulled whenever user logs in ?)

**Demo Link:** http://userdefaults-theme.surge.sh/

**Screenshots:** 

settings

### CODE REVIEW

**Comment by uday96** [comment]
@rishiraj824 @isuruAb @madhavrathi please review and suggest changes

**Comment by uday96** [comment]
@rishiraj824 yes. We need to have implementation based on user account only. I was implying that we can use this store to store the defaults, remove the hard coded configurations by fetching data from this store and initialising things. When the user logs in we just have to take the user data from the server and set the values in this userpreferences store and when he logs out, we push the userpreferences store data back to server. what do you think?

**Comment by rishiraj824** [comment]
@uday96 Okay. The only thing is it should save preferences when one chooses the theme preferences after logging in, closes the tab and opens it again, and sees that theme there. If that's the case it solves this issue.

**Comment by uday96** [comment]
@rishiraj824 yes, One can only choose preferences after loggin in. But shouldnt the default theme be rendered only when the user logs out and then logs in again? Otherwise he can simply use the change theme option right? Also, we need to push and pull userpreferences store data from the server to test this. That hasnt been implemented as of now. 

The basic idea of this store is :

* Store all the preferences / defaults for the user (which we would store on the server)
* Use these preferences upon initialisation / log-in to initialise the page (also helps in removing the hard coded configuration  -  https://github.com/fossasia/chat.susi.ai/issues/183) 
* Upon login pull user data from server and set the values in the userpreference store
* Upon logout push the data from the userpreference store to server
So the changes in this store can only be viewed after login - logout (when the pulling and pushing to server is also implemented)

**Comment by mariobehling** [comment]
Please ensure theme settings are saved on the server as well (might need to be implemented).

**Pull request merged**
