### PR TITLE
Added Share on facebook option

### PR DESCRIPTION
**Pull request by sayak119**
Fixes issue #798 

Changes: Added share on Facebook option.

Demo Link: http://obese-hate.surge.sh/

Screenshots for the change: 
screenshot from 2017-12-13 01-56-47

### CODE REVIEW

**Comment by sayak119** [comment]
@anshumanv can you check it now. It's working fine for me.

**Comment by anshumanv** [comment]
Seeing this - 
image

**Comment by sayak119** [comment]
@anshumanv that's because of the app Id. Facebook API provides you with one.

**Comment by sayak119** [comment]
screencast_wednesday-13-december-2017_02_01_17-ist

**Comment by sayak119** [comment]
@anshumanv @madhavrathi @isuruAb facebook is asking for Privacy policy for chat.susi.ai so that the app could be made public. Otherwise it would remain in the sandbox mode only

**Comment by sayak119** [comment]
@anshumanv can u recheck with the updated link please.

**Comment by anshumanv** [comment]
Works for me as well!

**Comment by sayak119** [comment]
@anshumanv @rishiraj824 can you please merge this ?

**Pull request merged**
