### PR TITLE
Parallelize the travis CI build

### LINKED ISSUE #1051: Parallelize the travis CI build
**Actual Behaviour**

Deployments and testing are appearing on a single instance

**Expected Behaviour**
They should be split up into multiple isolated instances

**Steps to reproduce it**

See a build log on travis ci

**Would you like to work on the issue?**

Yes working on it as par of GCI.

### PR DESCRIPTION
**Pull request by abishekvashok**
Parallelizes the travis ci build into multiple vm instances.
The instances are:
- Testing and getting code coverage matrix
- Deploying pr to surge
- Deploying non-prs

Also added functionality to build from all branches.

Fixes #1051

Demo Link: See the travis ci build (https://travis-ci.org/fossasia/chat.susi.ai/builds/328650006)

### CODE REVIEW

**Comment by abishekvashok** [comment]
Thanks @isuruAb

**Comment by abishekvashok** [comment]
@madhavrathi pls merge if feasable!

**Comment by madhavrathi** [comment]
@abishekvashok Thanks for your PR.

**Comment by abishekvashok** [comment]
Welcome @madhavrathi

**Pull request merged**
