### PR TITLE
Fixes: #664 - Store Custom theme settings in server

### PR DESCRIPTION
**Pull request by isuruAb**
Fixes issue #664 

Changes: 

- [x] Store Custom theme colours in server
- [x]  Load default theme data 
- [x] load theme data from server 

Demo Link: http://isuruab.surge.sh/

Screenshots for the change:

### CODE REVIEW

**Comment by madhavrathi** [comment]
@isuruAb Please check, the link is not working for me.
@dynamitechetan @saurabhjn76 Is it working for you guys?

**Comment by uday96** [comment]
@isuruAb Please check this 

er

The page doesnt load and the console gives this error ^

**Comment by saurabhjn76** [comment]
@madhavrathi No, it's not working for me, it is showing the same error as @uday96 mentioned. @isuruAb Please check

**Comment by madhavrathi** [comment]
@isuruAb The link is working fine now. Please resolve conflicts.
Thanks

**Pull request merged**
