### PR TITLE
Add scroll to top button

### LINKED ISSUE #2051: No Back to the Top button on the 'Blog' page
There is no 'Back to Top' button in the 'About' Pages, so you need to manually scroll up, which is kinda tedious, especially in the 'Blog' page.

**Would you like to work on the issue?**

Yep, I'm on it

### PR DESCRIPTION
**Pull request by AyushChatto**
Fixes #2051 

Changes: Added a back to top button on the blog page at the bottom-right for quickly scrolling to the top

Demo Link: https://pr-2052-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 
screenshot 2019-02-17 at 4 39 23 am

### CODE REVIEW

**Comment by AakashMallik** [comment]
@AyushChatto Also use the FAB button provided by MUI. That will take away a lot of the hardcoded styling that you have done. Better to rely on well-tested view library than hand-written code.

**Comment by AyushChatto** [comment]
@AakashMallik Thanks for taking the time out to explain. Made the necessary changes 👍

**Comment by AyushChatto** [comment]
> Was this bug introduces by the code you have added? Please verify this with the existing deployement and your surge link. @AyushChatto

Yeah it was, I'm not entirely sure why the changes made originally in Blog.css were doing this, but I've undone them, so I think I'm good to go 👍

**Comment by AyushChatto** [comment]
@fragm3 It's only on the blog page. Please navigate to the blog section (or follow the link at https://pr-2052-fossasia-susi-web-chat.surge.sh/blog), because I can see the button at the link, as seen in the screenshot. 

screenshot 2019-02-17 at 11 36 28 pm

**Comment by fragm3** [comment]
@AyushChatto shift the button closer to the bottom right edge

**Comment by AyushChatto** [comment]
@akshatnitd @fragm3 I moved it to {left: 60, bottom: 80}, because otherwise it was interfering with one of the options in the footer. I didn't check the surge link on a screen of a different size, so apologies for the oversight.

**Comment by AyushChatto** [comment]
@fragm3 @akshatnitd @AakashMallik I'm ready for a review :)

**Comment by fragm3** [comment]
@AyushChatto right: 70, bottom: 70 or 80,80 also looks fine.

**Comment by AyushChatto** [comment]
@fragm3 @akshatnitd done :)

**Comment by AakashMallik** [comment]
Update your branch...

**Comment by AyushChatto** [comment]
@akshatnitd I think we should be good. Sorry for the multiple forced pushes, was a bit unfamiliar with squashing. Hope this is good :)

**Pull request merged**
