### PR TITLE
Adds a toast message when speech recognition returns false

### LINKED ISSUE #1146: Mic container dialog box closes abruptly when speech recognition returns false
**Actual Behaviour**
The mic container dialog box abruptly disappears when the user doesn't give any speech input, or when the speech recognition returns false.

**Expected Behaviour**
The user should be alerted/prompted to give some speech input.

**Steps to reproduce it**
To reproduce the current behaviour, click on the mic icon on https://chat.susi.ai and do not give any speech input. The mic container dialog box will disappear abruptly.

**Would you like to work on the issue?**
Yes.

### PR DESCRIPTION
**Pull request by Akshat-Jain**
Fixes #1146 

**Changes:** Added a toast message when the user doesn't give any speech input, or when the speech recognition returns false.

**Demo Link:** https://pr-1146-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by isuruAb** [comment]
LGTM @rishiraj824  what do you think ?

**Comment by rishiraj824** [comment]
@isuruAb I think instead of an alert message, we can you use a dialogbox, or probably show the message in a better way. @Akshat-Jain

**Comment by Akshat-Jain** [comment]
@rishiraj824  Maybe a toast message ? What do you think ?

**Comment by isuruAb** [comment]
@Akshat-Jain  yeah that would be good

**Comment by Akshat-Jain** [comment]
@isuruAb Okay, will implement a toast message as soon as possible. Thanks :)

**Comment by Akshat-Jain** [comment]
@isuruAb @rishiraj824 Implemented the toast message. Please review and merge :)

**Pull request merged**
