### PR TITLE
Fixes #1498: Show avatar image on the App Bar

### LINKED ISSUE #1498: Add avatar image on the StaticAppBar
**Actual Behaviour**
* Not shown

**Expected Behaviour**
* Add avatar image on the StaticAppBar

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes #1498 

Changes: 
* Show avatar image on the App Bar
* Made relevant changes on the StaticAppBar and TopBar components

Demo Link: https://pr-1500-fossasia-susi-web-chat.surge.sh

Screenshots for the change: 

deepinscreenshot_select-area_20180803165650
deepinscreenshot_select-area_20180803165713

### CODE REVIEW

**Comment by akshatnitd** [comment]
Will resolve after #1504 gets merged

**Comment by akshatnitd** [comment]
The codacy error can be ignored, as it conflicts with eslint.

**Comment by akshatnitd** [comment]
@Akshat-Jain @anshumanv @hkedia321 Please review

**Comment by mariobehling** [comment]
In the next step please change this as follows:
* Make icon no larger than height of burger icon
* Add a better anonymous pic, e.g. similar to Twitter

**Comment by mariobehling** [comment]
Please follow up here: https://github.com/fossasia/chat.susi.ai/issues/1511

**Pull request merged**
