### PR TITLE
Added Hardware Connect functionality

### PR DESCRIPTION
**Pull request by betterclever**
Fixes issue #289 : Added the hardware connect functionality over websockets to Susi Hardware Device.
  
**Changes:** 
- Added connection Interface via websockets.
- Query received from Susi Hardware device after Speech Recognition is used to create a message in UI.
- Server Response from Susi API is send to Hardware Device for TTS,

**Demo Link:** N/A
**Screenshots for the change:** 
Functionality based change, I will provide a Youtube video of working implementation soon.

### CODE REVIEW

**Comment by betterclever** [comment]
@rishiraj824 @uday96 @isuruAb I am new to React so some implementations may be incorrect and not follow best practices, please review and point out.

**Comment by uday96** [comment]
@betterclever Once run `npm test` then you will see all the errors and the modifications needed. The lint test ensures that the code written is of good quality. Travis is failing because of lint test failure. Correct all the errors and push the code again :+1:

**Comment by betterclever** [comment]
Sure.

**Comment by betterclever** [comment]
@mariobehling This is some UI related part, I tried to do it but couldn't figure out the best way. An issue has been opened #303, so we shall continue in another PR. 
@rishiraj824 can you help me move that part to settings (UI Part only). Functionality wise, it is working.

@uday96 @rishiraj824 @isuruAb @madhavrathi Please review the PR once.

**Comment by rishiraj824** [comment]
@mariobehling I have moved the link to Settings in PR [#317](https://github.com/fossasia/chat.susi.ai/pull/317). Please merge this for https://github.com/fossasia/chat.susi.ai/pull/298

**Comment by betterclever** [comment]
Sample Deployment Link:  http://susiconnect.surge.sh/ 

@rishiraj824 @uday96  @isuruAb @mariobehling   Please review.

**Pull request merged**
