### PR TITLE
Fixes issue #823:Bottom text field disappears when search box on top is activated

### PR DESCRIPTION
**Pull request by RMCoder198**
Fixes issue #823:Bottom text field disappears when search box on top is activated

Changes:Now when search mode is on text area doesn't disappears.

Demo Link: http://red-reward.surge.sh/

Screenshots for the change: 
search

### CODE REVIEW

**Comment by RMCoder198** [comment]
@madhavrathi
Please review my commit

**Comment by RMCoder198** [comment]
@isuruAb 
This issue was created by @mariobehling .
Check issue no. 823 .

**Comment by isuruAb** [comment]
@RMCoder198  sorry for that. this was initially made as a feature.

**Comment by RMCoder198** [comment]
Ok ,i will fix it.

**Comment by RMCoder198** [comment]
@isuruAb 
How would i know whenever user sends a message. What file should i look for it.
I want to close the search bar whenever user sends a message to susi.

**Pull request closed without merging**
