### PR TITLE
Fixes #516 - Create a support page

### LINKED ISSUE #516: Create a support page
Model the support page after: https://api.ai/support/

### PR DESCRIPTION
**Pull request by rishiraj824**
Fixes issue #516

Changes: 
- Added a Support Page

Demo Link: 
http://susi-support.surge.sh/support

### CODE REVIEW

**Comment by madhavrathi** [comment]
Please remove underline as Isuru mentioned. Rest looks very good.

**Comment by rishiraj824** [comment]
@madhavrathi @isuruAb Please check now.

**Comment by mariobehling** [comment]
@rishiraj824 The support page is not linked from the other sites and does not have the correct color. Please follow up here: https://github.com/fossasia/chat.susi.ai/issues/590

**Comment by rishiraj824** [comment]
@mariobehling Will make the changes there. :+1:

**Pull request merged**
