### PR TITLE
Fixes #750 Fixed send button in firefox

### LINKED ISSUE #750: Input button disaligned in Firefox and not adhering to same design as in Chrome
screenshot from 2017-08-21 17-45-25

Please implement the enter button in the same way as in Chrome.

### PR DESCRIPTION
**Pull request by madhavrathi**
Fixes issue #750 

Changes: Fixed alignment of send button in Firefox.

Demo Link: http://firefoxfix.surge.sh/

Screenshots for the change: 
fire
@rishiraj824 @uday96 @isuruAb Please Review
Thanks

### CODE REVIEW

**Comment by mariobehling** [comment]
Still a different gray area next to the left of the button in FX.

screenshot from 2017-08-23 01-58-30

**Comment by madhavrathi** [comment]
@rishiraj824 @uday96 @isuruAb Are you guys having this gray area? In my Firefox browser, nothing like this is showing up.

**Comment by isuruAb** [comment]
@madhavrathi  no i don't 
screen shot 2017-08-23 at 9 10 02 am

**Comment by mariobehling** [comment]
@madhavrathi I am using FX 55.0.2 (64-bit) on Linux Mint.

**Comment by mariobehling** [comment]
Ok, let's see. I am merging this as it solves the problem for some and we can progress from here.

**Pull request merged**
