### PR TITLE
[WIP] Proposed Tab for Password

### LINKED ISSUE #1234: Implement Tab "Password" in settings
Add tab in "Password" in settings as below.

screenshot from 2018-05-25 01-07-20

### PR DESCRIPTION
**Pull request by prateekiiest**
Fixes #1234 
Changes: [Add here what changes were made in this issue and if possible provide links.]

Tab using `<input>` instead of `PasswordField`.

Only one field changed till now for Current Password

Demo Link: http://tan-writer.surge.sh/

@PrP-11 if we can collaborate on this it will be great :+1:

### CODE REVIEW

**Comment by PrP-11** [comment]
@prateekiiest Please see comment on #1234 .Thanks.

**Comment by PrP-11** [comment]
@prateekiiest I don't want to take any authorship or something. The point is if we double work on something it wastes the time and hard work of the developer. Therefore these rules are followed so that no duplicate work is done. Also @prateekiiest please follow fossasia's gitter channels to keep yourself updated with the work. @mariobehling specifically assigned this work to me and also we discussed about accounts in our weekly gsoc meets. Thanks

**Comment by prateekiiest** [comment]
Please see the updated demo link
http://tan-writer.surge.sh/

Sorry for the naive first commit


**Screen-shot**

screenshot 100

**Comment by prateekiiest** [comment]
@PrP-11 if you want you can take this further on.

I just saw the gitter channel and I am sorry I did not know that @mariobehling had assigned you this on gitter.
So if you wish it would be great if you can take it further on from now.

**Comment by prateekiiest** [comment]
`git fetch` and ( `git push` after squashing all the commits) on my local machine currently takes over a lot of time even under good network conditions. May be its due to the large file size of the git repository.

Any help on this?

**Comment by prateekiiest** [comment]
Ok, Thanks for making it work.
I am closing this

**Pull request closed without merging**
