### PR TITLE
Fixed links in overview page

### LINKED ISSUE #1341: Fix links to mobile clients
Right now we only have Android. Please fix the link to the play store on the overview page.

screenshot from 2018-06-15 19-50-01

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #1341 
Changes: (in Overview page)

- Android app link
- iOs app link
- Github Fossasia link

-A new page would open for Twitter, Facebook,  Line,  Slack, We Chat,  Viber,  Gitter. 

Demo Link: [https://pr-1341-fossasia-susi-web-chat.surge.sh](https://pr-1341-fossasia-susi-web-chat.surge.sh)

### CODE REVIEW

**Comment by fragm3** [comment]
Review now, passing.

**Comment by fragm3** [comment]
@daminisatya the changes pushed are not correct.

**Comment by anshumanv** [comment]
Your PR is incorrect @fragm3, please send a proper fix in the next pr.

**Comment by fragm3** [comment]
@anshumanv I did 2 commit, only the last commit is merged. Ill create a new PR!

**Comment by anshumanv** [comment]
Don't go by the commits, see the diff, everything's clear.

**Pull request merged**
