### PR TITLE
Fixes issue #796 -[ Enhance style and functionality of settings page]

### PR DESCRIPTION
**Pull request by tstreamDOTh**
Fixes issue #796 -[ Enhance style and functionality of settings page](https://github.com/fossasia/chat.susi.ai/issues/796)

Changes: 
- Added save button to each page
- Aligned text on right side pages on the left and implement similar padding to twitter
- Reduced the margin between left and right section of settings panel.
- Moved the "theme" option to a dedicated tab
- Changes the background color to match with susi.skills.ai

Demo Link: http://well-made-value.surge.sh/

Screenshots for the change: 
screen shot 2017-09-16 at 5 07 27 pm

### CODE REVIEW

**Comment by DravitLochan** [comment]
@tstreamDOTh Please fix the travis failing.

**Comment by tstreamDOTh** [comment]
@DravitLochan Yes. Working on it.

**Comment by tstreamDOTh** [comment]
I executed "npm run test", all tests are passing but travis-ci is failing at "npm run lint-js". Trying to resolve. If any suggestions or advice please let me know.

**Comment by DravitLochan** [comment]
@tstreamDOTh https://travis-ci.org/fossasia/chat.susi.ai/builds/276518258#L494-L691
these errors needs to be fixed.

**Comment by tstreamDOTh** [comment]
@DravitLochan It is failing due to this https://github.com/fossasia/chat.susi.ai/issues/805 I have tested the code locally with latest npm and it is passing all the tests.

**Comment by tstreamDOTh** [comment]
Making a fresh PR, closing this one.

**Pull request closed without merging**
