### PR TITLE
Modified Dark Background in Chat Section

### LINKED ISSUE #1142: Dark Theme Modifications
**Actual Behaviour**

The present dark theme is good. But we use Dark theme when working in low light or to save the battery Power and in present dark theme we have white background which is consuming more power and on the chat screen text is in greenish color which is readable but gives strain on eyes.

**Expected Behaviour**

1.Background color should be changed.
2.Text Color in Dark theme should be changed.

**Screenshots of the issue**

before dark theme chat

before settings dark theme

**Would you like to work on the issue?**

Yes!

### PR DESCRIPTION
**Pull request by singhrohan62**
Fixes #1142 

Changes: Updated the dark theme background in Settings and MessageSection Component 

Demo Link: https://pr-#1170-fossasia-susi-web-chat.surge.sh

Screenshots for the change:

### CODE REVIEW

**Comment by singhrohan62** [comment]
@psikarwal check the changes I have made now. I had to close the previous PR due to some unexpected changes 😅 . Btw, here are the screenshots : 
screenshot 55
screenshot 56
screenshot 58
screenshot 59

**Comment by duttaditya18** [comment]
@psikarwal I think the correct link is : https://pr-1170-fossasia-susi-web-chat.surge.sh/

**Comment by singhrohan62** [comment]
Sure @duttaditya18, but due to tight schedule as my exams are going in this week, I won't be able to make changes until this week. I will try my best to get the job done by next week.

**Comment by singhrohan62** [comment]
@duttaditya18 I have updated the branch.  By the way, "this is ready for merging" is one of the happiest things I wanted to hear this month:grin:

**Comment by mariobehling** [comment]
Good job!

**Pull request merged**
