### PR TITLE
Upgrade React v16.4, Material-ui, Remove onTouchTap fixes#1464

### LINKED ISSUE #1464: Update to React v16.4
**Actual Behaviour**

#1441 needs to be merged before proceeding.
#1463 is not needed if we upgrade as: React 16.4 removes a lot of internals (#121) this plugin depends on and will break the plugin. The drop down menu will work fine

**Expected Behaviour**

Upgrade to latest version

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #1464 

**Changes:**
1. Upgrade to React v16.4 and React-dom to v16.4
2. onTouchTap replaced by onClick
3. html-react-parser upgraded(older version had issue)
4. material-ui-responsive-menu, material-ui-scrollable-tabs were not being used anywhere.
5. Removed react-tap-event-plugin (injectTapEventPlugin)
6. Upgrade to newer material-ui@0.20.1

**Note:**

screen shot 2018-07-24 at 11 18 39 pm

Due to upgraded material-ui, above issue is occuring. Rest of the app is working fine

**Demo Link**: https://pr-1464-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by fragm3** [comment]
The travis is failing due enzyme v2.x not supporting react 16.4. Working on it.

**Comment by fragm3** [comment]
Following 5 tests falling: https://travis-ci.org/fossasia/chat.susi.ai/jobs/407752617, working on it.

**Comment by fragm3** [comment]
Following 3 tests failing:
screen shot 2018-07-29 at 8 30 36 pm

**Comment by mariobehling** [comment]
Please try to get tests to work. If not close the PR and open a new one, once the solution is clearer.

**Pull request closed without merging**
