### PR TITLE
Bottom right botton to show skills page fixes#1468

### LINKED ISSUE #1468: Implement top right button to show skills similar to Android
The Android app has a button on the top right of the screen to go to a skills screen. Please implement something similar in the chat app.

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #1468 

Changes: Added bottom right Button to show Susi Skills similar to Android

I can work on adding same bottom on settings, about, overview pages 

Demo Link: https://pr-1468-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by mariobehling** [comment]
Please implement this same as in the Android app. A skills page should move in from the right. Open sub issues if necessary.

**Comment by fragm3** [comment]
@mariobehling This can be done using a iframe which open up. I look into it today, what about merging this one?

**Comment by mariobehling** [comment]
> @mariobehling This can be done using a iframe which open up. I will look into it today, what about merging this one?

This does not solve the issue and is on the bottom instead of the top. Please look at the Android app. The goal is to implement it in the same way and all natively on this app. You can reuse the code from the skills cms.

**Comment by fragm3** [comment]
Working on it now.

**Comment by mariobehling** [comment]
@fragm3 I am closing this issue and would like to ask someone else to work on it. It looks like you are taking up a number of larger issues at the same time. Please only take up one issue at a time. This will help us to distribute the work and progress faster. I am closing this therefore.

**Pull request closed without merging**
