### PR TITLE
Fixes #591 - Redirect Docs to dev.susi.ai

### LINKED ISSUE #591: Change the link to an international page "Docs" to "dev.susi.ai"
Please delete the docs page and images and direct the link "Docs" to "dev.susi.ai".

### PR DESCRIPTION
**Pull request by uday96**
Fixes issue #591 

**Changes:**
* Removed current implementation of `Docs`
* Redirect Docs to http://dev.susi.ai/

**Demo Link:**  http://udaytheja.surge.sh/

@rishiraj824 @isuruAb @madhavrathi @mariobehling Please review

### CODE REVIEW

**Comment by uday96** [comment]
@rishiraj824 Made the changes. Thanks.
@mariobehling I have deleted the 3 images which were being used only by the docs page. The rest are being used in other pages

**Comment by rishiraj824** [comment]
Clicking on `/docs` on the Drawer takes me to this. Please check once.
screenshot from 2017-07-24 13 24 08

**Comment by mariobehling** [comment]
@rishiraj824 /docs is not needed anymore and we are not in production. So no need for redirects.

**Comment by rishiraj824** [comment]
@mariobehling  I was talking about the link which was supposed to be `dev.susi.ai`. It is taking to `http://udaythejs.surge.sh/http://dev.susi.ai` on clicking it.

**Pull request merged**
