### PR TITLE
Fixes #251: login now compatible with mobile

### LINKED ISSUE #251: Make login dialog in signup page compatible for mobile
**Actual Behaviour**

The width of login dialog on signup page is hard-coded, so not in mobile user has to swipe left or right in order to see full content

**Expected Behaviour**

making width in form percentage will resolve this issue.

**Screenshots of the issue**

loginissue

**Would you like to work on the issue?**

Yes, sending PR for it.

### PR DESCRIPTION
**Pull request by madhavrathi**
Fixes issue #251 

Changes: Width added in form of percentage.

Demo Link: http://compatible.surge.sh/

Screenshots for the change: 
pull

### CODE REVIEW

**Comment by madhavrathi** [comment]
@isuruAb @rishiraj824 @uday96 Please Review !
Thanks

**Comment by madhavrathi** [comment]
pull1

fixed button overflow. Please review @rishiraj824 @uday96 @daminisatya 
Thanks !

**Comment by madhavrathi** [comment]
@isuruAb Please check the link again. http://compatible.surge.sh/
Thanks

**Comment by rishiraj824** [comment]
@madhavrathi Please squash your commits into one.

**Pull request merged**
