### PR TITLE
Fix like/dislike button

### PR DESCRIPTION
**Pull request by k7un**
Fixes issue #952 

Changes:
User can undo like/dislike

Demo Link:
http://k7un.surge.sh

Screenshots for the change: 
Screenshot

### CODE REVIEW

**Comment by harshit98** [comment]
@k7un The pull request looks good to me. Please solve the Travis errors.

**Comment by anshumanv** [comment]
@k7un looks good, check travis, maybe @shreyanshdwivedi was working on it. Make sure he's okay with you fixing it.

**Comment by shreyanshdwivedi** [comment]
@k7un @anshumanv not a problem. You can proceed with the PR :smile:

**Comment by aashutoshrathi** [comment]
What are the changes made? 😕

**Pull request merged**
